### ISSUE TITLE
doc/tutorial/basics: generate tutorial from data and templates

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#10]
- keeping the links in sync is kind of tedious.
- would be nice to have some proper formatting
- use in-browser evaluation of example (using the GopherJS port)

**Comment by mpvl** [comment]
Examples are being unit tested now.

**Comment by mpvl** [comment]
Mostly done, remaining work is in cuelang/cuelang.org

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/10.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
