### ISSUE TITLE
vet --concrete=true always exits with code 0

### ISSUE THREAD

**Issue by gregwebs** [cuelang/cue#100]
vet --concrete=true outputs concrete errors to stderr. However, it always exits with code 0 if the errors are only concrete errors.

The desired behavior is that when `--concrete=true` is set, concrete errors should be treated the same as non-concrete errors. If there is an error (probably if anything is written to stderr), then the exit code should be 1.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/100.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
