### ISSUE TITLE
internal/core/eval: value alias does not work with list value

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1003]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +37bf801b linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export x.cue

-- x.cue --
package x

y: X = [1, 2, X[0]]
```

### What did you expect to see?

```
{
    "y": [
        1,
        2,
        1
    ]
}
```

### What did you see instead?

```
y.2: index out of range [0] with length 0:
    ./x.cue:3:17
```

My understanding from [the spec](https://tip.cuelang.org/docs/references/spec/#aliases) is that this should work, because only the value alias before a list _element_ is not yet implemented: this is before the list itself.

**Comment by mpvl** [comment]
It is correct that this should be supported. At the present it is not, though.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1003.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
