### ISSUE TITLE
cmd/cue: fmt rewrites valid value alias as let

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1004]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +37bf801b linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cp x.cue x.cue.golden
exec cue fmt x.cue
cmp x.cue x.cue.golden

-- x.cue --
package x

X={a: 1, b: 2, c: X.a}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> cp x.cue x.cue.golden
> exec cue fmt x.cue
> cmp x.cue x.cue.golden
[diff -x.cue +x.cue.golden]
 package x

-let X = {a: 1, b: 2, c: X.a}
+X={a: 1, b: 2, c: X.a}

FAIL: /tmp/testscript248389989/repro.txt/script.txt:3: x.cue and x.cue.golden differ
```

In this instance, the value is being used as an embedding, which should be ok?

**Comment by myitcv** [comment]
Per @mpvl this is working as expected.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1004.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
