### ISSUE TITLE
`cue fix` tries to align comments inside braces with those outside, causing weird field indentation

### ISSUE THREAD

**Issue by zellyn** [cuelang/cue#1006]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
`indent-bug-repro.cue`: 
```
x: {
	y: string

	// Comment
	z: string
} | "long_string_to_push_out_the_comment_on_this_line" // Comment
```

`cue fix indent-bug-repro.cue`

### What did you expect to see?
The same output as input

### What did you see instead?
```
x: {
	y: string

							// Comment
							z: string
} | "long_string_to_push_out_the_comment_on_this_line" // Comment
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1006.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
