### ISSUE TITLE
should output error messages to stderr

### ISSUE THREAD

**Issue by gregwebs** [cuelang/cue#101]
When cue emits this error message, it exits with code 1, but the error message is emitted to stdout. It should be emitted to stderr.

```
cmd must be run as one of its subcommands: unknown subcommand "getimage"
Run 'cue help cmd' for known subcommands.
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/101.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
