### ISSUE TITLE
cmd/cue: reference incorrectly allowed as value

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1010]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export file.cue --inject builtat=x

-- file.cue --
package x

built_at: int @tag(builtat,type=int)
```

### What did you expect to see?

An error regarding `x` not being parseable as a value of type `int`.

### What did you see instead?

```
built_at: reference "x" not found:
    builtat:1:1
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1010.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
