### ISSUE TITLE
cmd/cue: bad error message in the case bool value cannot be parsed

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1011]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export file.cue --inject builtat=x

-- file.cue --
package x

built_at: bool @tag(builtat,type=bool)
```

### What did you expect to see?

An error message about being unable to parse `x` as a `bool` value.

### What did you see instead?

An unrelated error message about environment variables:

```
invalid boolean value "x" for environment variable builtat
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1011.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
