### ISSUE TITLE
doc: Effective CUE

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1013]
**Is your feature request related to a problem? Please describe.**

The [tutorials](https://cuelang.org/docs/tutorials/) provide an excellent introduction to CUE, the language and its tooling.

The [CUE spec](https://tip.cuelang.org/docs/references/spec/), provides a reference manual for the language.

But there is a rather large gap in between these two extremes.

As has been discussed before, whilst we should aim for creating more tutorials, interactive guides and introductory material, it feels like there is a place for "Effective CUE", much like ["Effective Go"](https://golang.org/doc/effective_go) to answer the following question:

> How do I write clear, idiomatic CUE?

**Describe the solution you'd like**

To add "Effective CUE" as part of https://cuelang.org/, version along with the CUE language spec.

**Describe alternatives you've considered**

There is not really anything else that fills this gap at the moment. Or rather there are very scattered attempts in the form of answers to specific questions on GitHub Discussions, Slack etc. It feels like it will be more effective to pull this together in a central effort.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1013.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
