### ISSUE TITLE
encoding/openapi: remove use of deprecated identifiers

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1015]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Use of `encoding/openapi` requires using `cue.Runtime` and friends, all of which are deprecated. This triggers errors in tools like `staticcheck` that catch use of deprecated identifiers. 

### What did you expect to see?

An API which does not require using deprecated identifiers.

### What did you see instead?

As above.

Adding this as a tracking item; I will work on this as part of fixing up https://github.com/istio/tools/tree/master/cmd/cue-gen

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1015.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
