### ISSUE TITLE
cmd/cue: fmt indents too much sometimes

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#1018]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Format the following CUE source:

```cue
names: {
	categories: [
		"prometheus-operator",
	]
        kind:     "ThanosRuler"
        listKind: "ThanosRulerList"
        plural:   "thanosrulers"
        singular: "thanosruler"
}, scope: "Namespaced"
```

### What did you expect to see?

No change -- having `scope` positioned like that is weird for sure though. This is because of https://github.com/cuelang/cue/issues/826

### What did you see instead?

```cue
names: {
	categories: [
		"prometheus-operator",
	]
		kind:     "ThanosRuler"
		listKind: "ThanosRulerList"
		plural:   "thanosrulers"
		singular: "thanosruler"
}, scope: "Namespaced"
```

**Comment by myitcv** [comment]
Likely related/identical to https://github.com/cuelang/cue/issues/1006

**Comment by uhthomas** [comment]
Looks like it's actually even more common than I had first thought. Take this snippet:

```
// Some comment
some_long_key: "some_value"
```

Formatting results in

```
		// Some comment
some_long_key: "some_value"
```

Is this a regression? I don't remember seeing such behavior before.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1018.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
