### ISSUE TITLE
cmd/cue: fmt does not handle lists correctly

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#1023]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Given

```
a: [ "b"]
```

### What did you expect to see?

```
a: ["b"]
// or: (I don't know what cue fmt's preference is)
a: [ "b" ]
```

### What did you see instead?

No change.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1023.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
