### ISSUE TITLE
internal/core/eval: default not selected for field used in list arg passed to builtin

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1025]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa61ee7f linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue export

-- x.cue --
package x

import "strings"

#something: {
	image:    string | *"some default"
	toString: strings.Join([image], "")
}

x: #something
```

### What did you expect to see?

```
{
    "x": {
        "image": "some default",
        "toString": "some default"
    }
}
```

### What did you see instead?

```
> exec cue export
[stderr]
x.toString: non-concrete value *"some default" | string for element 0 of string list argument 0:
    ./x.cue:7:12
    ./x.cue:7:26
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1025.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
