### ISSUE TITLE
pkg/math: convert functions using float64 to arbitrary-precision decimals

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#103]
Most functions in `pkg/math` are using float64 as argument and return value type, since numbers in CUE are allowed to be arbitrary-precision decimals these functions should be converted to `*internal.Decimal` if possible.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/103.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
