### ISSUE TITLE
cmd/cue: fmt converts tabs to spaces in comments

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#1040]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Format

```cue
//	s	o	m	e	indented comment
```

### What did you expect to see?

No change.

### What did you see instead?

```cue
// s o m e indented comment
```

### Additional

This is a little strange and I'm not sure what the correct behavior is.

**Comment by myitcv** [comment]
Well that's an exciting bug! Confirmed with 0070bb104ee81630c7f5e962178f214ecbd2de6a using this less than ideal script:

```
exec cue eval --out text input.cue
cp stdout fmt.cue
cp fmt.cue fmt.cue.golden
exec cue fmt fmt.cue
cmp fmt.cue fmt.cue.golden

-- input.cue --
"// this\tis\ta\tcomment"
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1040.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
