### ISSUE TITLE
cue vet hangs with template, list and default value

### ISSUE THREAD

**Issue by philippseith** [cuelang/cue#1044]
With cue version 0.4.0 windows/amd64, the following combination of template, list, and default value causes cue vet/eval to hang causing high cpu load:

```CUE
A: #TypedObject & {
	childs: {
    	B : #TypedObject & {
    		//type: "int"
    	}
    }
}

#TypedObject : {
	type:    #Type | *"string"
	childs: [_] : #TypedObject
}

#Type: #BasicType | #ComplexType | [#BasicType] | [#ComplexType]
#ComplexType: [_] : #Type

 #BasicType: "int" | "uint" | "string"
````

It successfully runs either when the `A.childs.B.type` is set explicitly or `#Type` is defined without List support, eg. as `#Type: #BasicType | #ComplexType`. 

The same definition did work with cue 0.2.2

Strangely, relying on the default value for `A.type` does not cause cue to hang.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1044.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
