### ISSUE TITLE
cmd/cue: simplify ["k"]: v to "k": v

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#1045]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +20ed9abd linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue fmt -s x.cue
cmp x.cue x.cue.golden

-- x.cue --
package x

["^t"]: 5
-- x.cue.golden --
package x

"^t": 5
```

### What did you expect to see?

Test to pass.

### What did you see instead?

```
> exec cue fmt -s x.cue
> cmp x.cue x.cue.golden
[diff -x.cue +x.cue.golden]
 package x

-["^t"]: 5
+"^t": 5
```

As discussed with @mpvl, this would be a useful simplification so that the user can what they perhaps intended was not actually the case. Because `["^t"]` is equivalent to `"^t"`, whereas the user probably intended `[=~"^t"]` in this case.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1045.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
