### ISSUE TITLE
Unification of imported struct with top-level struct

### ISSUE THREAD

**Issue by joshburkart** [cuelang/cue#106]
I'd like to create a schema for an entire file. I have a struct `ConfigFile` defined in a package `"blah.com/schemas"`:

```
// pkg/blah.com/schemas/config.cue

package schemas

ConfigFile: {
    records: [...ConfigRecord]
}
ConfigRecord: {
    param1: string
    param2: int
}
```

I tried to use it as follows in a new file:

```
// demo.cue

import "blah.com/schemas"

schemas.ConfigFile & {
    records: [
        {
            param1: "blah"
            param2: 7
        },
        {
            param1: "yesss"
            param2: -5
        },
    ]
}
```

...but it doesn't seem to work:

```
 $ cue eval demo.cue 
expected label or ':', found '.' :
    ./demo.cue:5:8
missing ',' in file:
    ./demo.cue:16:3
terminating because of errors
```

...even though replacing `ConfigFile` with its value from `config.cue` works fine:

```
// demo.cue

import "blah.com/schemas"

{
    records: [...schemas.ConfigRecord]
} & {
    records: [
        {
            param1: "blah"
            param2: 7
        },
        {
            param1: "yesss"
            param2: -5
        },
    ]
}
```

...and yields:

```
 $ cue eval demo.cue 
records: [{
    param1: "blah"
    param2: 7
}, {
    param1: "yesss"
    param2: -5
}]
```

(Also for the record I'm really enjoying experimenting with Cue!)

**Comment by mpvl** [comment]
They are essential in making closed structs workable.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/106.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
