### ISSUE TITLE
exec.Run runner of kind "XXX" not found with k8s resources

### ISSUE THREAD

**Issue by b4nst** [cuelang/cue#1061]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

I'm still trying to cut down my module in order to send something short that reproduces my issue.

```cue
command: deploy: {
	apply: exec.Run & {
		r:                  release.#Release
		stdin: r.output
		cmd:   "cat"
	}
}
```
`r.output` being a string generated by a `yaml.MarshalStream` of a list in `release.#Release`. This list contains Kubernetes definitions.

I've noticed that if I use `yaml.Marshal(single-resource)` it works. It does not work with a list comprehension + `strings.Join` (same error)
The command works if I replace `exec.Run` by `cli.Print` with proper changes (`stdin` --> `text`, remove `cmd`)

### What did you expect to see?

Command executed with sucess (prints `r.output` content)

### What did you see instead?

Prints `r.output` content then exit with error 

```
runner of kind "XXX" not found
```

XXX being the `kind` value of the first resource displayed (e.g. `Deployment`)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1061.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
