### ISSUE TITLE
YAML exports with strings in certain formats are interpreted as datetimes

### ISSUE THREAD

**Issue by lytedev** [cuelang/cue#1076]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

It looks like I'm using the latest release.

### What did you do?

```
echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml | yq
```

### What did you expect to see?

```
echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml | yq
{
  "service": {
    "port_mappings": [
      "2222:22"
    ]
  }
}
```

### What did you see instead?

```
{
  "service": {
    "port_mappings": [
      133342
    ]
  }
}
```

# Reasoning

YAML supports some date/time formats, and the unquoted `2222:22` is interpreted as a base60 float. So any string in this format with a port on the right less than 60 will be interpreted this way.

Cue should either wrap all strings in quotes or detect this format and wrap it in quotes to protect you.

**Comment by lytedev** [comment]
Possibly related: https://github.com/go-yaml/yaml/issues/34

**Comment by lytedev** [comment]
My workaround for this, for anybody who cares, was to output JSON (`cue ... --out json`) which any YAML deserializer should handle just fine.

**Comment by verdverm** [comment]
This seems more like a problem with `yq` and Yaml 1.1 vs 1.2+ (looking through the go-yaml issue you linked

```
$ echo 'service: port_mappings: ["2222:22"]' | cue eval - --out yaml
service:
  port_mappings:
  - 2222:22
```

This looks to be valid YAML 1.2+

Also, which `yq` are you using

This one works fine https://github.com/mikefarah/yq/releases/tag/v4.9.6

**Comment by lytedev** [comment]
This also happens with `docker-compose`, to be clear. I just used `yq` as a quick way to demonstrate the problem. Also, if you refer to this comment on the linked issue, you can see that these YAML deserializers/parsers are following the spec for parsing what my Cue intended to be a string as a base-60 float: https://github.com/go-yaml/yaml/issues/34#issuecomment-55772666

**Comment by verdverm** [comment]
It's been more than 10 years since YAML the 1.2 spec was written. Should the parsers be updated at this point? I'm not sure what CUE has said about how far back it supports various specs... not sure if there is a link anywhere. I only know for Go it is the same versions that the Go team supports.

**Comment by niemeyer** [comment]
go-yaml has indeed never supported the float 60 representation as it's a bad idea (spec 1.2 confirms that), but it does marshal such values as quoted strings to prevent them from being interpreted incorrectly by old parsers. So it doesn't look like that specific output was generated by go-yaml v3.

Here is how it would handle it:

https://play.golang.org/p/Y0Qg72VW2p1

**Comment by verdverm** [comment]
@niemeyer is the general (simple?) idea to quote any string which has a colon when emitting?

**Comment by niemeyer** [comment]
No, we check the actual syntax of 1.1 base 60. This is also far from being the only edge case in that regard. See bools on 1.1 vs. 1.2, for instance.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/1076.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
