### ISSUE TITLE
Using parentheses for line continuation

### ISSUE THREAD

**Issue by joshburkart** [cuelang/cue#109]
This works:

```
a = [1, 2, 3]
b = [4, 5]
blah: (a + b)
```

But this doesn't appear to work:

```
a = [1, 2, 3]
b = [4, 5]
blah: (
    a +
    b
)
```

It instead produces:

```
expected ')', found newline:
    ./a.cue:11:6
missing ',' in struct literal:
    ./a.cue:12:1
terminating because of errors
```

Is there some reason why this doesn't appear to be possible at the moment? Is there a workaround for breaking up long lines? Thanks!

**Comment by mpvl** [comment]
Yes, it is the same reason this won’t work in Go: the comma insertion rules (semicolon in Go) will insert a comma after the `b`, which is ungrammatical in this case. It’s the price to pay for mostly not having to write commas, while still retaining a simple scanner/parser. 

The workaround is put out the closing parenthesis on the same line as the `b`. I’m afk, so you may want to verify.

**Comment by joshburkart** [comment]
Ah ok! Reasonable workaround for now. Thanks!

**Comment by mpvl** [comment]
Yes, just verified.
```
a = [1, 2, 3]
b = [4, 5]
blah: (
	a +
	b)
```
works. I wouldn't know how to fix so that your example works, except for changing the grammar in weird ways or complicating the scanner.

Here is the Go equivalent: https://play.golang.org/p/MLGleL2rZun

**Comment by joshburkart** [comment]
So I guess it'd require some undesirable coupling of different interpreter components? The component that inserts commas would have to be able to be aware of parenthesis level?

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/109.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
