### ISSUE TITLE
spec/comprehension: if clause is missing else

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#111]
atm. the only way to implement a `else` is to add the same `if` clause and negating the expression
```
foo: ["dragons"]

if ((foo & string) != _|_) {
  bar: foo
} 
if ((foo & string) == _|_) {
  bar: 20
} 
```
while this works, it feels strange from a user perspective coming from other languages.
I also checked the spec and it seems to be missing https://github.com/cuelang/cue/blob/master/doc/ref/spec.md#comprehensions

**Comment by mpvl** [comment]
It is not missing, it was deliberately omitted. I’m not entirely against adding it, but only after getting more data and experience
And seeing how comprehensions develop. Conditional expression tend to lead to awful configurations, and although comprehensions are grammatically not expressions, they are getting close and just might develop into those.

**Comment by mpvl** [comment]
BTW, note that the above could be approximated as:
```
{
  foo: string
  bar: foo
} | {
  foo: [...] 
  bar: 20
}
```
Disjunctions will often be a good approach for more complicated structural alternatives.

**Comment by mpvl** [comment]
You could even fully simulate `else` with default values:
```
{
  foo: ["dragons"]

 *{
    foo: string
    bar: foo
  } | *{
    foo: int
    bar: 10
  } | {
    bar: 20
  }
}
```
where only the else block is not marked as a default. Note you can have multiple defaults, which makes sense to use if there is a discriminator field, like in this case.

**Comment by xinau** [comment]
@mpvl Thanks for the input.

**Comment by seh** [comment]
> You could even fully simulate `else` with default values:

I discovered today that this example works up until the "foo" field has a value that's a string or an int. If it matches either of the first two disjunction alternatives, we have to ensure that it **doesn't** match the third as well.

We need something like the following in the third alternative:
```
foo: null | bool | bytes | float | [...] | {...}
bar: 20
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/111.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
