### ISSUE TITLE
cue: add regular expression support

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#12]
Allow constraining string values with regular expressions:

```
a: re("[a-z][a-z][a-z]")
a: "foo"
```

The syntax is yet to be determined. But see  #1.

**Comment by mpvl** [comment]
implemented

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/12.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
