### ISSUE TITLE
doc/ref: add contents to language specification

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#121]
It would be great if the [spec](https://github.com/cuelang/cue/blob/master/doc/ref/spec.md) had a set of contents at the start similar to the Go spec, to enable easy navigation to a point of interest and a quick scan of the sections.

**Comment by mpvl** [comment]
Mirroring it in cuelang.org should give that for free. I’m preparing to move over the tutorial as well.

**Comment by mpvl** [comment]
cuelang.org push process now copies spec into contents, thereby generating a TOC.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/121.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
