### ISSUE TITLE
cmd/cue: doesn't like files starting with a period

### ISSUE THREAD

**Issue by mvdan** [cuelang/cue#123]
```
$ cue trim .drone.cue
no CUE files in command-line-arguments
terminating because of errors
$ sed 3q .drone.cue

pipeline default: {
        // Notes on the Go setup:
```

/cc @rogpeppe

**Comment by mpvl** [comment]
This seems to be inherited from the Go logic on which CUE is based. (Go has the same behavior.) But in the case of cue it makes fully sense to allow this.

**Comment by mvdan** [comment]
Yes, it's fairly common for `cue import` to end up with "dot files". Imagine `.travis.yml` or `.drone.yml`. I hope that the fix won't be too invasive.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/123.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
