### ISSUE TITLE
cmd/cue: select best quoting mechanism when importing

### ISSUE THREAD

**Issue by mvdan** [cuelang/cue#124]
Imagine the yaml below:

```
cmds:
  - printf "%s" $FOO
```

This will end up something like `"printf \"%s\" $FOO"`. It would be nicer if it instead avoided the backslashes, like `#"printf "%s" $FOO"#`.

Perhaps it could do the same for multi-line strings and other common scenarios. This isn't about saving bytes, but about readability.

/cc @rogpeppe

**Comment by mpvl** [comment]
A general "pretty quoter" is somewhat non-trivial, which is why I haven't done it yet.

But I agree this would be better.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/124.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
