### ISSUE TITLE
cmd/cue: incorrect command seems to print garbage

### ISSUE THREAD

**Issue by mvdan** [cuelang/cue#125]
```
$ cue foo
command command "foo" is not defined
&{0xc00027a500 0xc00027a500 0xc00027a780 true} Run 'cue help' to show available commands.
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/125.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
