### ISSUE TITLE
cmd/cue: failure on `_tool.cue` files

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#127]
If I run `cue vet` or `cue eval` on a file with a `_tool.cue` suffix, it fails with `no CUE files in command-line-arguments`. It should not ignore files explicitly specified on the command line.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/127.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
