### ISSUE TITLE
importing package with same name as source package fails

### ISSUE THREAD

**Issue by sev3ryn** [cuelang/cue#133]
Importing package with same name as used in source file causes resource leak and fails with:
```
import failed reading dir /Users/sev3ryn/cue/pkg/github.com/testuser/testpkg: readDir: open /Users/sev3ryn/cue/pkg/github.com/testuser/testpkg: too many open files:
    ./source.cue:4:2
```

To reproduce - consider folder structure like this
```
├── pkg
│   └── github.com
│       └── testuser
│           └── testpkg
│               └── test.cue
└── source.cue
```

source.cue:
```
package testpkg

import (
	t "github.com/testuser/testpkg"
)

id: string
body: t.Body

```

**Comment by mpvl** [comment]
This was fixed a while back. Sorry for not having the commit handy.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/133.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
