### ISSUE TITLE
encoding/openapi: paths attribute is missing

### ISSUE THREAD

**Issue by eadlam** [cuelang/cue#134]
Openapi specs are generated without a paths attribute, which is a required attribute. This breaks client generation with the openapi-generator tool. 

We should add `paths:{},` to the generated openapi specs.

**Comment by eadlam** [comment]
Fix: https://cue-review.googlesource.com/c/cue/+/3420

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/134.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
