### ISSUE TITLE
pkg: Add function user.Current()

### ISSUE THREAD

**Issue by tredoe** [cuelang/cue#135]
The current user would be very useful at some configurations.
Please add it when you have any time. Thanks!

https://golang.org/pkg/os/user/#Current

**Comment by mpvl** [comment]
A "current user" value breaks hermiticity (or pureness, if you will) and cannot be included in configurations. 

However, it would be possible to insert it as as part of the scripting layer, if that works for you.

**Comment by tredoe** [comment]
Yes! It was be to be used at the scripting layer.

**Comment by mpvl** [comment]
So it would live the in `pkg/tool/user` or `pkg/tool/os/user`.

**Comment by mpvl** [comment]
The simplest would be to make a task to produce the user, as it fits within the current framework. Nicer perhaps, in this case, would be to make it a normal library call. In that case, we would first have to ban the usage of the tool packages in regular CUE files (See Issue #126).

**Comment by tredoe** [comment]
> So it would live the in `pkg/tool/user` or `pkg/tool/os/user`.

I'd decide `pkg/tool/os/user` to follow the Go's packages structure.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/135.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
