### ISSUE TITLE
VS Code Syntax Highlighting

### ISSUE THREAD

**Issue by apobbati** [cuelang/cue#137]
Is there a VS code extension for syntax highlighting planned in the near future?

**Comment by jlongtine** [comment]
Andrew Hodges put one together: https://github.com/betawaffle/vscode-cue

It works well!

Friedrich Nietzsche – "Freedom is the will to be responsible to ourselves."

**Comment by apobbati** [comment]
It works! Thanks

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/137.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
