### ISSUE TITLE
cue: references to ancestor nodes should be direct and not through outer scope

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#152]
If a struct is referred to (and copied), any reference within this copy to the root of the struct should resolve to the root of the copied struct.

Both these cases below should work. 
```
a: {
  b: int
  c: a.b  // workaround: use b, intstead of a.b
}
d: a & { b: 2 } // a.c == 2

Foo: {
   foo?: Foo
   bar:  string
}
foo: Foo & {
	foo: {
		bar: "a"
	}
	bar: "b"
}
```
See also Issue #145

**Comment by mpvl** [comment]
Or maybe the way it is now is actually correct. Depending on how a references is interpreted, a reference to root should bind to the copy or not, but it should probably be consistent.

**Comment by rudolph9** [comment]
@mpvl Yeah I could see either case being valid but in either case ties back in to the discussion around the `@` notation on the [Proposal: Querying extension](https://github.com/cuelang/cue/issues/165)

**Comment by rudolph9** [comment]
Relevant comment to this this issue `https://cuelang.slack.com/archives/CLT3ULF6C/p1574377972082800?thread_ts=1574376537.080000&cid=CLT3ULF6C`

**Comment by mpvl** [comment]
I'm pretty convinced the current behavior is correct now. It is just unfortunate there is this dichotomy. Field aliases mitigate it a bit, as one can alias a possibly shadowed variable.

I think it will be possible to detect when users make a mistake and then warn them in a vet command, similar to what Go does.

**Comment by mpvl** [comment]
Closing for now.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/152.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
