### ISSUE TITLE
Able to add fields to closed structs

### ISSUE THREAD

**Issue by lukealonso** [cuelang/cue#153]
Exporting the following:

```
Foo: {
	listOfCloseds: [...Closed]
}

Closed :: {
	a: int | *0
}

Junk: {
	b: 2
}

Foo & {
	listOfCloseds: [{
		for k, v in Junk {
			"\(k)": v
		}
	 }]
}
```

outputs:

```
{
    "listOfCloseds": [
        {
            "a": 0,
            "junk": 2
        }
    ]
}
```

which seems incorrect, since we shouldn't have been able to add an extra field to a struct unified with Closed.

**Comment by xinau** [comment]
@mpvl it seems like this is a bug with the struct comprehension as the following works.
```
Foo & {
	listOfCloseds: [Junk]
}
// listOfCloseds.0: field "b" not allowed in closed struct:
```
Do you have a idea where their is a good place to start looking ?

**Comment by mpvl** [comment]
@xinau at the evaluator in the cue subdirectory. Most likely binop.go.

I usually copy a snippet in to TestX in resolve_test.go and start debugging from there.

**Comment by xinau** [comment]
@mpvl. Thank you for the information. will do so next time.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/153.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
