### ISSUE TITLE
cue: Value.Eval can lose information

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#157]
The following code prints 
```
kind 0b1000000; op 0 {
kind 0b100; op 0 {
```
indicating that the result is a struct containing a single `int`, but this loses the bounds information of the `x` field inside the struct. I would expect to see an `&` operation too.

```
package main

import (
	"fmt"
	"log"

	"cuelang.org/go/cue/parser"
	"cuelang.org/go/cue"
)

func main() {
	var runtime = new(cue.Runtime)
	inst, err := runtime.Compile("x.cue", `
V :: {
	x: int
}
X :: {
	<_>: int64
} & V
v: X
`)
	if err != nil {
		log.Fatalf("compile: %v", err)
	}
	expr, err := parser.ParseExpr("lookup.cue", `v`, parser.DeclarationErrors, parser.AllErrors)
	if err != nil {
		log.Fatalf("parseExpr: %v", err)
	}
	v := inst.Eval(expr)
	v.Walk(func(v cue.Value) bool {
		op, _ := v.Expr()
		fmt.Printf("kind %#b; op %d {\n", v.IncompleteKind(), op)
		return true
	}, nil)
}
```

**Comment by mpvl** [comment]
This particular example is correct. But indeed inserting a `Value.Eval` in the mix causes the error.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/157.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
