### ISSUE TITLE
Allow cmd to read external data from env and command line flags

### ISSUE THREAD

**Issue by UkiahSmith** [cuelang/cue#159]
To what extent should environment variables and flags be unified?

How should the cmd command evaluate environmental variables and flags when both are specified.

**Comment by mpvl** [comment]
The tooling layer now supports environment variables. 

A general mechanism for injecting values based on command lines flags is now supported through `--inject/-t`. This is not general command line flags, which may still be considered, but it is actually surprisingly hard to get a nice UX for. So closing this for now until `--inject/-t` proves insufficient.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/159.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
