### ISSUE TITLE
problems with operators

### ISSUE THREAD

**Issue by jba** [cuelang/cue#16]
```
a: [1] + [2]
```
gives
```
unsupported op +(list, list)
```
at current master (7d0797babe691ebe185ea6b89801d65b265d953a).

**Comment by jba** [comment]
In addition:
- List equality also seems to be missing
- The spec says `%` is for floats, but the code expects duration or int. (`matchBinOpKind` in `kind.go`.)

**Comment by mpvl** [comment]
fixed for numbers

**Comment by enisoc** [comment]
Just to add to the todo list, it seems that one of the operators used in the [tutorial](https://cue.googlesource.com/cue/+/HEAD/doc/tutorial/basics/operators.md) isn't implemented yet:

```
c: 3 * "blah"
```

```
unsupported op *(number, string):
```

**Comment by mpvl** [comment]
Multiplication of strings and bytes now supported.

**Comment by mpvl** [comment]
all of the mentioned operations are fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/16.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
