### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by jtrakk** [cuelang/cue#162]
I'm wondering if CUE might support Python bindings.

As far as I know, the simplest and most [widely supported](https://doc.pypy.org/en/latest/extending.html) interfaces are via [CFFI](https://cffi.readthedocs.io/), as in [this Go example](https://github.com/nils-werner/python-go-cffi). Binaries can be distributed in the [wheel format](https://www.python.org/dev/peps/pep-0427/) on [PyPI](https://pypi.org/).

**Comment by mpvl** [comment]
This could live in a `cuelang` repo, like `cuelang/lang-python` is someone wants to take this on.

**Comment by mpvl** [comment]
@jtrakk could you perhaps comment on which features you would want to expose in the API. The API of CUE is quite large.

**Comment by jtrakk** [comment]
Even a minimal set of features could be useful. For example, translation between CUE strings and built-in Python types (or even JSON strings) would be enough to get started with CUE if it were packaged on PyPI so I could just `pip install` it.

**Comment by bep** [comment]
SInce Cue is a Go project, it would probably make sense to look at https://github.com/google/starlark-go

**Comment by mbarkhau** [comment]
This project has been created in the meantime: https://pypi.org/project/pycue/

It's a [wrapper](https://github.com/tebeka/pycue/blob/master/cue.py) around the `cue` CLI command.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/162.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
