### ISSUE TITLE
cmd/cue: 'cue mod init' creates an anonymous module

### ISSUE THREAD

**Issue by masiulaniec** [cuelang/cue#169]
```
$ cue mod init example.com
$ cat cue.mod/module.cue 
module: ""
$ 
```
I was expecting `module: "example.com"`.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/169.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
