### ISSUE TITLE
doc/ref: the "field constraint" language feature is unspecified

### ISSUE THREAD

**Issue by masiulaniec** [cuelang/cue#170]
I've learned about it by accident while reading https://godoc.org/cuelang.org/go/pkg/strings

> Some of the functions in this package are specifically intended as field constraints. For instance, MaxRunes as used in this CUE program
> 
> ```
> import "strings"
> 
> myString: strings.MaxRunes(5)
> ```
> specifies that the myString should be at most 5 code points.
>

**Comment by mpvl** [comment]
The design of this feature is still in progress. The usage of this function won't change depending on the outcome, though.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/170.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
