### ISSUE TITLE
cmd/cue: add yaml support to export command

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#182]
Eventhough json is a subset of the yaml specification from a end-user perspective who is reading wants to read yaml files it might make sense to support for "pretty" yaml as well in the export command.

It probably is also easy to implement as cue already has support for marshaling yaml in the encoding package.

cue version
```
$ cue version
cue version 0.0.14 linux/amd64
```

**Comment by mpvl** [comment]
There is already flag for this (`--out`), it just needs add support for yaml, which already exists indeed.

It currently packages do not output comments, but that is a separate topic (requires port to go-yaml v3, which has additional benefits as well).

**Comment by xinau** [comment]
What are the other benifits of using go-yaml v3 besides comments ?

**Comment by mpvl** [comment]
@xinau: it supposedly has an AST that allows extracting position information, which means I can get rid of internal/yaml (and remove a maintenance burden). It would also allow getting raw anchor and translate them into equivalent CUE constructs.

**Comment by mpvl** [comment]
Done. Does not output comments yet, but that is a different issue.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/182.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
