### ISSUE TITLE
Allow to explicitly choose the format in `cue vet`

### ISSUE THREAD

**Issue by suhr** [cuelang/cue#183]
So it would be possible to do something like `cue vet --format json backlog.data task.cue`

**Comment by mpvl** [comment]
This seems useful. The question is what would be a good API. For instance, we could alternatively allow overrides for individual files, like: `cue vet json:backlog.data task.cue`

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/183.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
