### ISSUE TITLE
Question about spec.md

### ISSUE THREAD

**Issue by vlulla** [cuelang/cue#187]
Shouldn't the rule for `simple_bytes_lit` be 
```
simple_bytes_lit     = `'` { unicode_value | interpolation | byte_value } `'` .
```
instead of 
```
simple_bytes_lit     = `"` { unicode_value | interpolation | byte_value } `"` .
```
?

**Comment by mpvl** [comment]
Yep absolutely. Will send a fix now.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/187.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
