### ISSUE TITLE
Wrong link in the cue tour

### ISSUE THREAD

**Issue by nlewo** [cuelang/cue#197]
This link is not correct https://github.com/cuelang/cue/blob/master/doc/tutorial/basics/2_types/40_stringlit.txt#L17

**Comment by mpvl** [comment]
Did you verify this link on cuelang.org? The tutorial in this repo is meant to be the source for the tour in repo, which will do rewriting of the files.

**Comment by nlewo** [comment]
Marcel van Lohuizen <notifications@github.com> writes:

> Did you verify this link on cuelang.org? The tutorial in this repo is meant to be the source for the tour in repo, which will do rewriting of the files.

Yep, I noticed this error on the cuelang.org tour.
So, in the page:
https://cuelang.org/docs/tutorials/tour/types/stringlit/, the link
https://cuelang.org/docs/tutorials/tour/types/stringlit/interpolation.md
is not found:
```
Not found

Oops! This page doesn't exist. Try going back to our home page.
```

**Comment by mpvl** [comment]
Ah, the link was correct, it was just that the latest CUE repo including the fix was not yet included in cuelang.org.

**Comment by nlewo** [comment]
Ok, thx.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/197.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
