### ISSUE TITLE
Setting inner field using folding

### ISSUE THREAD

**Issue by MatanRubin** [cuelang/cue#198]
In [Folding of Single-Field Structs](https://cuelang.org/docs/tutorials/tour/intro/fold/) there are some examples of folding single field structs.
Based on the examples, I thought the following would work:
```
Foo :: {
    bar: string
}

Baz :: {
    foo: Foo
}

baz: Baz & {
    foo: bar: "hello"
}
```

When running it, I get the following message which I don't really understand:

```
$ cue eval -ic example.cue
missing ',' in struct literal:
    ./simple.cue:10:9
terminating because of errors
```

The following _does_ work:
```
Foo :: {
    bar: string
}

Baz :: {
    foo: Foo
}

baz: Baz & {
    foo: {
        bar: "hello"
    }
}
```
And the output is as expected:
```
$ cue eval -ic simple.cue
baz: {
    foo: {
        bar: "hello"
    }
}
```

What am I doing wrong?

**Comment by rudolph9** [comment]
what version of cue are you running?  I have the v0.0.14 release and 
```
package main

Foo :: {
    bar: string
}

Baz :: {
    foo: Foo
}

baz: Baz & {
    foo: bar: "hello"
}
```
works as expected:
```
:!cue eval %                                                                                                                                                                                                                                                                                                                                             
Foo :: {
    bar: string
}
Baz :: {
    foo: {
        bar: string
    }
}
baz: {
    foo: {
        bar: "hello"
    }
}

**Comment by MatanRubin** [comment]
Was using v0.0.11. Upgraded to the latest and it works as expected.
Note to self: always make sure I'm running the latest version before opening an issue :-)
Thanks!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/198.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
