### ISSUE TITLE
Does someone from core want to submit a talk to CfgMgmtCamp?

### ISSUE THREAD

**Issue by purpleidea** [cuelang/cue#212]
Hi, I'm part of the organizing team for the upcoming https://cfgmgmtcamp.eu/ghent2020/ in Ghent. If someone would like to submit a very technical cue talk, we'd love to have it! Let me know ASAP =D

Thanks!

**Comment by mpvl** [comment]
That will almost certainly work for me. I'm not far away and Belgium is awesome. :)

Feel free to contact me directly.

**Comment by purpleidea** [comment]
Great!

@mpvl Best thing to do is just submit to the CFP listed above, and ping me when done. Any questions, also feel free to ping. I'm purpleidea on Freenode IRC or email in git log.

Cheers!

**Comment by mpvl** [comment]
Okay, will do tomorrow or latest in the weekend, if okay. Intense day tomorrow!

Thanks!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/212.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
