### ISSUE TITLE
Export os.Getenv as a go builtin

### ISSUE THREAD

**Issue by bastianccm** [cuelang/cue#213]
To be able to consume environment variables in Cue it would be super helpful to access `os.Getenv`, in the same way the go standard library works.
I would propose to export this function as a new `os` package withing `pkg`.

https://cue-review.googlesource.com/c/cue/+/4343

**Comment by mpvl** [comment]
This is planned to be included as a task type for the tooling later for v0.0.16.

It cannot be a builtin for normal packages as it would break hermeticity.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/213.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
