### ISSUE TITLE
Improvement: replacing the existing yaml adaptor with go-yaml-v3

### ISSUE THREAD

**Issue by vnzongzna** [cuelang/cue#216]
Supporting the #182 `go-yaml v3` would also help with
* Easy translation of achors and references to CUE
* Improved positioning
* Comments

**Comment by mpvl** [comment]
This holds both for parsing and generating. This would replace `internal/third_party/yaml`.

This would be a good test:
```
{
        a: &a ~,
        b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a],
        c: &c [*b,*b,*b,*b,*b,*b,*b,*b,*b],
        d: &d [*c,*c,*c,*c,*c,*c,*c,*c,*c],
        e: &e [*d,*d,*d,*d,*d,*d,*d,*d,*d],
        f: &f [*e,*e,*e,*e,*e,*e,*e,*e,*e],
        g: &g [*f,*f,*f,*f,*f,*f,*f,*f,*f],
        h: &h [*g,*g,*g,*g,*g,*g,*g,*g,*g],
        i: &i [*h,*h,*h,*h,*h,*h,*h,*h,*h],
    }
```

See https://github.com/dtolnay/serde-yaml/issues/53.

**Comment by ahpook** [comment]
One acceptance criteria for this change: `cue export --out yaml` should represent the order of the fields in each data structure the same as `cue export`. Currently `yaml.Marshal` reorders them lexically.

**Comment by ahpook** [comment]
This is in cf727960 , I can confirm the sorting is correct now; not sure about the other improvements @vaibhavk was thinking of.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/216.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
