### ISSUE TITLE
cue: cue eval hangs up on recursive definition with default value

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#217]
Cue hangs up (presumably with an infinite loop) when trying to run `cue eval` on the following code:

```
package tst

x: {
	a: A
	b: A
}

A :: string | [A]
```

This is with commit 275105a3c865a7444b9552bb115ab1c7db3c088b.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/217.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
