### ISSUE TITLE
cue export: wrong status code and error not written to stderr

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#218]
Run `cue export` on the following code:

```
package tst

a: b: {
	c: a.x
}
```

The error gets printed to the standard output, not the standard error, and the status code is zero.

```
$ cue export .
cue: marshal error at path a.b.c: undefined field "x"
$ echo $?
0
$ cue export . > /dev/null
$
```

**Comment by mpvl** [comment]
Yeah, that should be printed to stderr.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/218.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
