### ISSUE TITLE
Unable to export cue file having number as a key

### ISSUE THREAD

**Issue by hjain98** [cuelang/cue#219]
a.json
```
{
 "20": "a"
}
```

cue import a.json gives
a.cue
```
20: "a"
```

running:
```
$ cue export a.cue
missing ',' in struct literal:
    ./a.cue:1:3
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/219.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
