### ISSUE TITLE
should tutorials int16 range positive limit start with a '.'?

### ISSUE THREAD

**Issue by patflynn** [cuelang/cue#22]
I was a little surprised to see the '.' here:
https://cue.googlesource.com/cue/+/HEAD/doc/tutorial/basics/rangedef.md

`int16     >=-32_768 & <=.32_767`

**Comment by mpvl** [comment]
That’s a typo.

**Comment by mpvl** [comment]
fixed

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/22.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
