### ISSUE TITLE
Hex literals

### ISSUE THREAD

**Issue by suhr** [cuelang/cue#226]
To specify a binary enum in Kaitai Struct YAML, it's convenient to use hex literals:

```
enums:
  type_tag:
    0: end_of_content
    0x1: boolean
    0x2: integer
    0x3: bit_string
...
```

I'd like to use CUE instead of YAML for Kaitai Struct. But it finds out that you can't use hex literals in CUE.

**Comment by mpvl** [comment]
Would you expect this create a map of integers to strings or a map of strings to strings? For instance, would `0x1` and `0x01` represent the same key?

**Comment by mpvl** [comment]
CUE currently does not support integer maps, although this is being considered.

**Comment by suhr** [comment]
Good questions. JSON maps can use only strings as keys while YAML maps seem to be able to use any value as a key.

Anyway, I'm strongly against any implicit type conversions.

PS: Kaitai Struct seems to support string hexadecimal as keys too. So maybe this feature of YAML is not really necessary.

**Comment by mpvl** [comment]
I'll close this then for now, as there is already a proposal to allow integer indexes (included in query proposal).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/226.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
