### ISSUE TITLE
BUG: uint (i.e. uint32) compared to 1 << 62 

### ISSUE THREAD

**Issue by rudolph9** [cuelang/cue#227]
I came across this when v0.0.15 wouldn't compile with gopherjs
[This check](https://github.com/cuelang/cue/blob/master/cue/builtins.go#L1850) 

I've filed an [issue with gopherjs](https://github.com/gopherjs/gopherjs/issues/951) since technically it compiles in go but not gopherjs.

But, it seems like an oversight in the cue impl since `i` is a uint `uint` from the received context will never be greater than `1<<32` and branch based on the conditional would never be executed.  I believe it's akin to an ` if false` branch...

Perhaps I am mistaken through and it does serve the intended purpose, if that is the case could we adjust the impl from
```
1850: if i > 1<<62 {
```
to
```
1850: if uint64(i) > uint64(1)<<62 {
```
to work around the bug in gopherjs and help support the [npm cuelang package](https://github.com/cuelang/cue/issues/86)

**Comment by mpvl** [comment]
Could you try if changing the return type for `uint()` from `uint` to uint64`?  (And similarly that for `int()` from `int` to `int64`)? That should fix it.

**Comment by rudolph9** [comment]
@mpvl If I'm understanding you correctly 
> (And similarly that for int()frominttoint64`)?

Is referring to the argument passed to `Bit` [here](https://github.com/cuelang/cue/blob/master/cue/builtins.go#L1853)

Which results in an error:
```
$ gopherjs build -o ./build/__CUE__.js ./src/cue.go
../../../.golang/src/cuelang.org/go/cue/builtins.go:1853:20: cannot use int64(i) (value of type int64) as int value in argument to x.Bit
``` 

https://golang.org/pkg/math/big/#Int.Bit

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/227.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
