### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by trebe** [cuelang/cue#23]
With this code
```
x: {a:1}|{a:2}
y: x & {a:3}
```

I get the following not so helpful message:

```
empty disjunction: &{{0xc0001fe600} <nil> <nil> [] [{4 0xc00007ee00 <nil> <nil>}] 0xc0001eed20}:
    /...<filename>:2:4
    
terminating because of errors
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/23.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
