### ISSUE TITLE
ISO8601 / RFC3339 String Validation

### ISSUE THREAD

**Issue by rawkode** [cuelang/cue#239]
Is is possible to validate a string value against ISO8601 / RFC3339?

Maybe going further than that, could it be added as a Cue primitive?

**Comment by xinau** [comment]
@rawkode Their already exists a builtin for verifying if a string matches a RFC3339 formated data. It's located in the `time` package and the function is called `Time`. You may also want to take a look at the package documentation https://godoc.org/cuelang.org/go/pkg/time. I hope this comment helps you. :)

**Comment by rawkode** [comment]
Thank you, @xinau 👍

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/239.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
