### ISSUE TITLE
BUG: != applied to disjunction before structural cycle is concrete

### ISSUE THREAD

**Issue by rudolph9** [cuelang/cue#241]
cue version: 42346df8456e476a484323b2ae8128fec8e512d4

The following yields an error:
```
Value :: 0 | 1

foo: Value
foo: != bar
bar: Value
bar: != foo
```

```
:!cue eval bug.cue --all
foo: empty disjunction: invalid value 0 (excluded by !=(0 | 1)):
    ./scratch.cue:4:6
    ./scratch.cue:1:9
bar: error evaluating bound:
    ./scratch.cue:6:6

shell returned 1
```

However, the following doesn't:

```
Value:: 0 | 1

foo: Value
foo: != bar
bar: Value
bar: != foo

bar: 0
```

```
:!cue eval bug.cue --all
Value :: 0 | 1
foo:     1
bar:     0
```

**Comment by rudolph9** [comment]
likely related https://github.com/cuelang/cue/issues/242

**Comment by mpvl** [comment]
The error message may be unhelpful, but that does seem like an invalid cycle to me.
I am guessing that you expected unevaluated CUE. That is strictly more correct in the above case, although in both cases, exporting results in an error.

Note that at attempting to making

**Comment by rudolph9** [comment]
Here are test cases cover this issue https://github.com/rudolph9/cue/compare/bd2173eb2c9ffa4b75bc43c9b36dbd19caf0e196...rudolph9:gh-242

**Comment by rudolph9** [comment]
Testing out the [0.3.0-alpha1](https://github.com/cuelang/cue/releases/tag/v0.3.0-alpha1), the bug appears to be fixed!

```
cell: a:  0 | 1
cell: a:  != cell.b
cell: b:  0 | 1
cell: b:  != cell.a
cell: b:  0
```

```
:!cue eval --concrete fiename.cue                                                                                  
cell: {
    a: 1
    b: 0
}
```

```
cell: a:  0 | 1
cell: a:  != cell.b
cell: b:  0 | 1
cell: b:  != cell.a
cell: a:  1
```

```
:!cue eval --concrete fiename.cue                                                                                  
cell: {
    a: 1
    b: 0
}
```

I'll leave the issue open until changes are included in a non-alpha release.

**Comment by mpvl** [comment]
See https://github.com/cuelang/cue/blob/master/cue/testdata/cycle/issue241.txtar

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/241.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
