### ISSUE TITLE
eval to undefined should be able to exit with a non-zero error code

### ISSUE THREAD

**Issue by gregwebs** [cuelang/cue#248]
I have a script that interacts with the cue CLI. It does an `eval` in several places based on user input. If the user input is wrong, cue will return an undefined value.

```
 ./output/bin/cue eval foo.cue  -e foo
_|_ // reference "foo" not found
```

This output is probably helpful for a user interaction. From a scripting interaction it is very annoying. The backwards compatible way to improve scripting is to exit with a non-zero code. If you really want to stay backwards compatible, add a `-e` option that turns on the exit code (`jq` actually does exactly this).

**Comment by mpvl** [comment]
I'm fine with returning a non-zero exit code and am surprised it doesn't.

What would be the benefit of not returning a non-zero exit code there? And what are the reasons `jq` would return a zero exit code in case of an error?

Thanks!

**Comment by gregwebs** [comment]
The only benefit I see is backwards compatibility

**Comment by mpvl** [comment]
I am willing to take that risk. I think any reasonable person would expect a non-zero code here.

I looked at the `-e` flag of `jq` and it can be useful in some cases, though.

**Comment by gregwebs** [comment]
The only benefit when retrieving a single field now is backwards compatibility. There might be a benefit for more complex retrievals, but I don't do those.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/248.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
