### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by leoluk** [cuelang/cue#250]
Is anyone working on an IntelliJ plugin?

With the strong typing of Cue, such a plugin would be highly useful (and probably hard to write). Basic syntax highlighting should be a lot easier.

**Comment by leoluk** [comment]
Turns out, the native IntelliJ TextMate Bundle support loads https://github.com/betawaffle/vscode-cue just fine. That sorts out basic syntax highlighting!

**Comment by leoluk** [comment]
Feature request for native support: https://youtrack.jetbrains.com/issue/IDEA-242301

Consider voting for the issue.

**Comment by verdverm** [comment]
I am unable to vote or comment, but I'm not sure it best fits under tools.Kubernetes (they just added that label over there)

It's a language, and probably belongs where those are.

**Comment by bwplotka** [comment]
Is there any way we can collaborate together to create one? open source / community driven? (: Anyone up for it?

**Comment by leoluk** [comment]
Yes, there's a powerful plugin SDK that can be used to implement this.

**Comment by leoluk** [comment]
Did anyone start working on a plugin? I'd be happy to contribute.

**Comment by leoluk** [comment]
Work on this has started, we're over at #intellij on Slack

**Comment by myitcv** [comment]
Related: https://github.com/cuelang/cue/issues/142

**Comment by jansorg** [comment]
The plugin on the JetBrains Marketplace: https://plugins.jetbrains.com/plugin/16126-cue

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/250.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
