### ISSUE TITLE
Allow additional (non-cue) files to be specified alongside --package

### ISSUE THREAD

**Issue by gatesn** [cuelang/cue#254]
```
cue vet -p foo  # Works ok
cue vet foo.yaml cue.foo  # Works ok
cue vet -p foo foo.yaml  # Fails requiring explicit cue files to be defined
```

**Comment by mpvl** [comment]
Main issue: the command line should at least allow non .cue files together with a cue single package.

Another issue is that `-p` is not supported for `vet`. But perhaps it shouldn't be.  Note that fixing  `cue vet x.yaml .:foo` already would support selecting packages.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/254.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
