### ISSUE TITLE
cmd/cue: add "generate" command

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#26]
Analogous to the Go's `go generate`.

CUE's is designed with code generation in mind and it is to be expected that many CUE files will be generated. A cue:generate directive would allow annotating the methods used to generate the files in a way familiar to Go programmers.

**Comment by mpvl** [comment]
The obvious thing to do is to add a `command: generate:` entry in the tool layer. Until this is proven to be awkward, we archive this option.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/26.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
