### ISSUE TITLE
Completely missing yaml map values cause unhelpful error message

### ISSUE THREAD

**Issue by zellyn** [cuelang/cue#262]
When a map (or other) value is just completely missing in yaml files, `cue vet` prints only line numbers from the cue schema it is checking against. When vetting hundreds of files, this then requires some kind of manual binary search to find the offending yaml file.

```
mkdir cuetest
cd cuetest
echo -e 'foo:\n\n' > test.yaml
echo 'foo: {}' > test.cue
cue vet test.yaml test.cue
foo: invalid operation null & {} (mismatched types null and struct):
    -
    ./test.cue:1:6
```

**Comment by mpvl** [comment]
Interesting, the issue here is that the map has no token, and thus no position. Hopefully the move to yaml.v3 will fix this.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/262.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
