### ISSUE TITLE
Validation and Duplicates have the same text in website

### ISSUE THREAD

**Issue by atakanyenel** [cuelang/cue#263]
I'm not sure if it's intended but https://cuelang.org/docs/tutorials/tour/intro/validation/ and https://cuelang.org/docs/tutorials/tour/intro/constraints/ have the same explanation.

Some other observations:
- Duplicates lead to : -> https://cuelang.org/docs/tutorials/tour/intro/constraints/ (endpoint is constraints)

- In validation the sentence "If a constraints defines a concrete" should be ".. a constraint", no plural.

**Comment by mpvl** [comment]
And it is ironically called duplicates. That was not the point though. :)

The first link is not longer in the repo and thus there seems that something has gone wrong with the latest deploy. Similarly the type is also fixed. Looks like a new integrate is in order.

Thanks!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/263.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
