### ISSUE TITLE
spec: part of struct section renders badly

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#265]
This doesn't look right to me (specifically the italic `"foo"` and the part after "shorthand for:):

![image](https://user-images.githubusercontent.com/66491/72596585-26b0e100-3904-11ea-86ab-d98d5478f16e.png)

**Comment by mpvl** [comment]
Seems to be (one of the many) Hugo bugs. I'll try triple quoting

**Comment by ahpook** [comment]
Looks like this is happening because of the MathJax javascript plugin, which is set up to interpret sequences in square brackets `[ ... ]` and process them as LaTeX.

**Comment by mpvl** [comment]
looks fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/265.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
