### ISSUE TITLE
cmd: migrate from cobra to jpillora/opts

### ISSUE THREAD

**Issue by wxio** [cuelang/cue#27]
Please take a look at https://github.com/jpillora/opts/tree/subcommands (work in progress). I think cue is a fascinating project and happy to contribute (I have started a similar project using protobufs as starting point). 

Thought helping move from Cobra to Opts might be a good first start.

Related to #25,  #9

One of this nice things about the work in progress on Opts is basic bash, zsh and fish command completion is free and highly customisable  for more complex requirements.

**Comment by mpvl** [comment]
What would be the benefit from moving to jpillora's package?

One reason to use Cobra is that Cobra is used by many of the tools that CUE is likely to be used in concert with (like Kubernetes). For instance, does it use POSIX flag semantics, or Go, or something else?

Also, I prefer to use more stable packages, even if they are less desirable. This package is too young.
But it is worth considering once it stabilises. I expect the command lines options and so on to require an overhaul once they are all defined (make flags consistent). That may be a good point to consider this. 

Protobuf support is on the TODO list for CUE. That may be a better focus. :)

**Comment by mpvl** [comment]
Closing this for now. Cobra is awkward in a lot of ways, but it is familiar and under control.

The code is slowly abstracting away from it, but using something else does not make sense until there is a rewrite later.

**Comment by marco-m** [comment]
For what is worth, for the future reconsideration, I used both https://github.com/jpillora/opts and https://github.com/alexflint/go-arg. I selected go-arg as my library of choice. It supports subcommands.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/27.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
