### ISSUE TITLE
cannot restrict open struct

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#271]
This succeeds when it should be an error because `[_]: _ & close("a": string)` should not allow any fields other than `"a"`.
```
T :: [_]: _
T :: close({"a": string})
x: T
x: {
	a: "hello"
	b: "foo"
}
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/271.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
