### ISSUE TITLE
cmd/cue: cue trim does not guarantee unchanged output

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#277]
Using a custom build at commit 442bf2d94d4a71f63a2ffd28c6e437790fbe3284.

Run `cue trim` on the following file:

```
[_]: x: "hello"

a: x: "hello"
```

The output is :
```
[_]: x: "hello"
```
which is not the same thing - the `a` field has been dropped.

**Comment by mpvl** [comment]
In addition, trim should really run a before and after diff to verify its results are correct as an extra safeguard.

**Comment by rogpeppe** [comment]
This seems to have been fixed since 442bf2d. I can't reproduce the issue any more.

**Comment by rogpeppe** [comment]
actually, it appears not to be fixed. https://cue-review.googlesource.com/c/cue/+/4909 goes into an infinite loop on the above example.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/277.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
