### ISSUE TITLE
cmd/cue: trim: format an empty struct without an extra line

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#278]
When all fields in a struct are redundant, it's common for `cue trim` to produce the empty struct (`{}`), but this is always formatted on two lines, for example:

```
z: a: {
}
```
rather than:
```
z: a: {}
```

This means that even though data has been removed, structs that go from having a single field to having none will actually increase the total number of lines.

Consider formatting the empty struct without an intervening newline to make this case nicer.

**Comment by rogpeppe** [comment]
It could be argued that `cue fmt` should always remove whitespace in an empty struct.

**Comment by mpvl** [comment]
The easiest fix seems to be formatting `{}` on a single line. I'll be down for that if there are no objections.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/278.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
