### ISSUE TITLE
cmd/cue: unexpected result from two-stage comprehension

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#287]
I'd expect the following code to produce `{z: true}` but it produces `{}` instead:

```
if E["x"] != _|_ {
	E :: y: true
}
if E["y"] != _|_ {
	z: true
}
E :: [_]: bool
E :: x: true
```

**Comment by mpvl** [comment]
From Slack: Currently, all comprehensions are evaluated before they are mixed in. This means that the second comprehension cannot see the y inserted by the first one. However, it probably makes more sense to adopt a fixed-point semantics, where embeddings and comprehensions are evaluated until a fixed point is reached. There is also an odd consequence with the current semantics where comprehensions may be evaluated anyway if structs with comprehensions are passed around, effectively executing the next step in a fixed-point computation.

**Comment by mpvl** [comment]
See https://github.com/cuelang/cue/blob/master/cue/testdata/comprehensions/issue287.txtar

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/287.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
