### ISSUE TITLE
cmd/cue: cue fmt -s can break expressions in strings

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#294]
Running `cue fmt -s` on the following code:

    "\("x")": 1

produces:

    "\(x)": 1

which is semantically very different (and broken).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/294.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
