### ISSUE TITLE
UniqueItems constraint not respected

### ISSUE THREAD

**Issue by robsonmeemo** [cuelang/cue#299]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version (devel) darwin/amd64
</pre>
Compiled from HEAD at d05ea952e37160e206b0bfc9ec86b179ecebf09c

### Does this issue reproduce with the latest release?
yes

### What did you do?

```
import "list"
x: list.UniqueItems
x: [string, ...string]
x: ["x","x"]
```

### What did you expect to see?
Error

### What did you see instead?
```
x: ["x","x"]
```

**Comment by mpvl** [comment]
This is a known issue related to the evaluator. The plan is to fix this as part of the evaluator redo after the next release.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/299.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
