### ISSUE TITLE
support exit code for custom commands

### ISSUE THREAD

**Issue by garethr** [cuelang/cue#30]
I was experimenting with adding a set of validation commands to my cue configuration, in `_tools.cue` files. The commands they exec out to will return non-zero exit codes when those commands fail, but running them via the `cue <cmd>` runner eats those exit codes and always returns 0. Checking the code this doesn't appear to be something I can add to the `print` task.

https://github.com/cuelang/cue/blob/2b0e7cd9f63a190e762d7c802b98528ff80dcb7c/cmd/cue/cmd/custom.go#L299-L310

Is there a way of achieving this at present? Supporting passing through the exit codes would make integration of cue commands into pipelines easier.

**Comment by mpvl** [comment]
Yes, it makes sense to at least return a non-zero error code on failure. To what extent does it need to be the same code? As there may be multiple tasks executed concurrently, returning the code of the failed first task may result in indeterministic behavior, so simply returning 1, for instance, may be a better approach.

**Comment by garethr** [comment]
Agreed, returning `1` makes sense in all the cases I have in mind.

**Comment by garethr** [comment]
Thanks, just tested this out and this works for me. Appreciated.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/30.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
