### ISSUE TITLE
cmd/cue: trim fails on valid code

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#303]
On tip (commit c1b5e62), I see this issue. It's not a regression (the same thing happens in v0.0.15):

```
exec cue vet -c foo.cue
exec cue trim foo.cue

-- foo.cue --
package example

foo: c: true
foo: M
M :: c?: bool
```

I get this failure:

```
foo: field "c" not allowed in closed struct:
    ./foo.cue:3:9
```

Note that the previous `cue vet -c` call succeeds fine.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/303.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
