### ISSUE TITLE
cue fmt: misplaced open brace in list iterator

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#305]
On tip (commit a920a11f10f1c982d1da5ddabf4a973ea41955bd)

The following code:

```
questions: [
	{
		a:    "b"
	} for q in []
]
```

formats as:
```
questions: [
            {
        a: "b"
    } for q in []
]
```

The opening brace looks like it's in the wrong place.

**Comment by mpvl** [comment]
Probably makes no sense to fix this, as this construct will be removed soonish.

**Comment by mpvl** [comment]
This construct is now removed. The new construct does not seem to suffer from this issue.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/305.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
