### ISSUE TITLE
cmd/cue: cue fmt doesn't work well with multiple-package directories

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#308]
commit 6dfecc3cc062c910ea9f610f06a122780b71ba3d

Although multiple packages in a single directory are allowed, it's hard to format the files.
```
exec cue fmt ./...

-- x.cue --
package x

-- y.cue --
package y
```

This fails with: ```
found packages "x" (x.cue) and y (y.cue) in "$WORK"
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/308.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
