### ISSUE TITLE
trailing newline not allowed in \() string interpolation

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#309]
on tip (commit f89aa48)

The following cue file doesn't parse:

```
x: "\(
	345
)"
```

It gives this error:

```
expected ')' for string interpolation:
    ./n.cue:4:5
missing ',' in struct literal:
    ./n.cue:5:4
```

The specification says:

> `\(` must be followed by a valid CUE Expression, followed by a `)`.

And the above expression is valid.
Removing the newline after the `345` fixes the issue, but this should not be necessary.

**Comment by mpvl** [comment]
Not saying it’s good UX, but it is according to spec. Comma insertion rules insert a comma at the new line, which means it’s no longer a valid expression.

**Comment by rogpeppe** [comment]
> Comma insertion rules insert a comma at the new line, which means it’s no longer a valid expression.

I don't understand why it's not a valid expression when there's a trailing newline.
This piece of cue works fine, for example:

```
123,
```

**Comment by rogpeppe** [comment]
ah, but this doesn't:

```
(123,)
```

I understand better now :) It'd still be good to fix.

**Comment by mpvl** [comment]
@rogpeppe, aside from convenience, how would you justify a trailing comma in `"\(foo,)"?

Either way, I looked at what Swift does, from where this construct was copied, and they take the following approach: for single-line strings there may be no newline separating `\(`, expr, and `)`. For multiline strings there may be a newline on both ends. I like that approach as a compromise.

**Comment by rogpeppe** [comment]
> aside from convenience, how would you justify a trailing comma in `"(foo,)"?

Convenience seems like a reasonable argument to me. After all, Go allowed trailing commas in function arg lists and other places for a similar reason. This doesn't seem so different to me.

**Comment by mpvl** [comment]
It is a bit different in that argument lists are lists, and this is a single value. I'm inclined to take the Swift approach though. It keeps single-line strings as single-line strings and can be relaxed later if need be.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/309.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
