### ISSUE TITLE
cmd/cue: cue export -out fails in an unexpected way

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#312]
on tip (commit f89aa483a05b267a0581ad3b84134d2d9490a3aa)

I was accidentally forgetting the double-hyphen for the `--out` flag on `cue export`.
It took me a long time to work out what I was doing wrong, because of this result:

```
% cue export -out x.cue
encoding: cannot convert incomplete value "!=\"\"" to JSON:
    types.cue:12:19
```

This also happens with `-o ut`, but not (apparently) with any other argument.

**Comment by mpvl** [comment]
That seems to be at least a Cobra bug, as `-u` is not a valid option.

**Comment by myitcv** [comment]
With https://cue-review.googlesource.com/c/cue/+/5260 applied, the output is:

```
unknown shorthand flag: 'o' in -out
```

**Comment by mpvl** [comment]
> With https://cue-review.googlesource.com/c/cue/+/5260 applied, the output is:

Well that's odd, especially because there _is_ a shorthand flag 'o'.

**Comment by mpvl** [comment]
See  https://cue-review.googlesource.com/c/cue/+/5322.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/312.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
