### ISSUE TITLE
pkg/time: support conversion of time to unix

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#319]
Currently we can convert from unix seconds to RFC3339 but not vice-versa.
It would also be nice to be able to add dates, etc.

**Comment by antong** [comment]
I was looking for a way to write constraints on time fields, such as to require a field to be within a certain time range. I think having a function to convert to UNIX time would help. When you say "add dates, etc.", do you mean expose functions for time arithmetic like the Go time.Sub(), Add(), AddDate() and so on? I think that would be useful. And being able to convert to UNIX time would allow to do this with the durations that can already be parsed and validated by the time package.

About time constraints, If I understand correctly the time values as handled by the time package are actually RFC3339Nano formatted strings. (If this is so, we should probably document it. I didn't see it explicitly stated in the package doc.) As the doc says, RFC3339Nano doesn't necessarily sort correctly, so I feel a bit uneasy about that. But I guess it can only sort incorrectly between values that fall within the same second.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/319.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
