### ISSUE TITLE
export field with type string return error

### ISSUE THREAD

**Issue by sah4ez** [cuelang/cue#32]
I have cue file `test.cue`:
```
address: string
```
And when I call this, I got an error: 
```
$ cue export test.cue 
json: error calling MarshalJSON for type cue.Value: json: error calling MarshalJSON for type cue.Value: cannot convert incomplete value "string" to JSON
```

**Comment by mpvl** [comment]
Working as intended. Feedback welcome as in how tool or docs can be clearer.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/32.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
