### ISSUE TITLE
cmd/cue: obscure error from disallowed field

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#321]
commit 52cc7f11efb7567a2e9da3690a61fbaacbcca3bb

The error from running `cue vet` on the following code is obscure:

```
X :: [=~ "^x"]: _|_
X :: [_]: _
x: X
x: {
	a: "hello"
	b: 2345
	x: 45
}
```

The error I get is:
```
x.x: from source:
    ./m.cue:1:17
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/321.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
