### ISSUE TITLE
cmd/cue: unused import prevents definition

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#322]
The following code prints a spurious error because (presumably) the unused import causes the identifiers in `x.cue` not to be processed.
```
! exec cue vet
cmp stderr expect-stderr

-- expect-stderr --
imported and not used: "strings":
    ./x.cue:2:8
-- x.cue --
package x
import "strings"

foo: "hello"

-- y.cue --
package x

bar: foo
```

The error I see is:

```
imported and not used: "strings":
    ./x.cue:2:8
bar: reference "foo" not found:
    ./y.cue:3:6
```

Unused imports should be the last thing checked, I think (as in Go).

**Comment by mpvl** [comment]
Not sure I understand this. Would it be okay to see both errors, or is the main problem that the "not used" error is reported in the presence of others?

**Comment by mpvl** [comment]
Note that `foo` is actually in file `x` and actually should be found. If that is the error you saw it is fixed now. I'm not quite sure what you expected to see, but I'll go with that this is fixed.

**Comment by rogpeppe** [comment]
Yes it seems like that was why the error was spurious. If v it's fixed now, then great!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/322.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
