### ISSUE TITLE
cmd/cue: incomplete string interpolation in struct key is ignored

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#326]
commit 76252f4b7486cf862b0ee4113bbb3c91092d8d11

Running `cue export` on the following code succeeds without error:

```
x: {
	"\(string)": "v"
}
```

It produces:

```
{
    "x": {}
}
```

I'd expect to see an "incomplete value" error because of the incomplete value in the field string interpolation.

In the original case that prompted this issue, the string interpolation expression contained a reference to a unknown field, which caused a silent and hard-to-diagnose failure.

**Comment by verdverm** [comment]
```
v: {
  "\(string)": "string"  // bug?
  "\(int)": "int"        // bug?
  "\(bool)": "bool"      // ok, gives interpolation input type error
}
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/326.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
