### ISSUE TITLE
tool: task types should be closed

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#327]
commit 76252f4b7486cf862b0ee4113bbb3c91092d8d11

I misspelled `$after` as `after` and nothing complained. It would have been very helpful if it had (i.e. task types should be closed definitions to avoid misspelled field names).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/327.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
