### ISSUE TITLE
pkg/encoding/xml support

### ISSUE THREAD

**Issue by rudolph9** [cuelang/cue#330]
# WIP

## Summary
Support for:
* `Marshal`
* `Unmarshal`
* `Valid`
* `Schema` 
  * returns a cuelang value which constrains the struct return by `Unmarshal` and used as input to `Marshal.  

This package would allow for lossless converting to and from XML. This would be an MVP approach focusing on a Cuelang representation according to the [w3 REC-xml-20081126 spec][xml-spec] with focus on usability from the perspective of Cuelang and extensibility allowing for eventual support of common XML schemas and extensions (e.g [DTD](https://en.wikipedia.org/wiki/Document_type_definition), [XSD](https://en.wikipedia.org/wiki/XML_Schema_(W3C)), etc). 

This would be similar to `pkg/encoding/json` with but unlike JSON there is not a clear one-to-one mapping to/from Cuelang/XML. Best effort made to balance user friendliness with open ended design to eventually support common XML schemas and extensions.

## Approach

Using a lossless cuelang schema for capturing XML data such that cuelang can be programmatically converted to and from XML. Conversion will happen by `import "encoding/xml"` and `xml.Unmarshal(string|byte) // => xml.Schema & xmlValue` to convert a string representation of an xml document to a cuelang struct constrained by `xml.Schema` and `xml.Marshal(xml.Schema & xmlValue) // => xmlString`.

### Example
Without putting consideration into usability; the `xml.Schema` could follow the schema defined by existing xml-to-json converters given cuelang is a superset of json. A browser based accessible version can be found [here](http://www.utilities-online.info/xmltojson/). The input to `xml.Unmarshal` and return of `xml.Marshal` would be the left pane. The input to `xml.Marshal` and return of `xml.Unmarshal` would be the right pane.  A rough impl of `xml.Schema` would be defined as follows:
```
XML :: {
  NameRegex :: =~ "[^-].*" // quick and dirty better def found here https://www.w3.org/TR/2008/REC-xml-20081126/#NT-Name
  AttrRegex :: =~ "-.*"
  XmlSchema :: {
    [NameRegex]: {
      "#text"?: string | [...string]
      [NameRegex]: XmlSchema
      [AttrRegex]: string
    }
  }
}
```
xmlString:
```
<?xml version="1.0" encoding="UTF-8" ?>
	<hello>
		<world planet="earth">!</world>
	</hello>
```
xmlValue
```
{
  "hello": {
    "world": {
      "-planet": "earth",
      "#text": "!"
    }
  }
}
```
The converter used in the above example takes some liberties such as order of keys in a json object are not guaranteed and therefore not guaranteed to be lossless. Also, it's not particularly user friendly. A lot more could be done on top of this using Defintions in the schema. 

### Additional considerations
Preferably, all info in the original XML doc would should be captured in something that can be exported as raw json and any user friendly convinces could be defined using Defintions and programmatically filled taking unifying `XmlSchema & xmlValue`.

The logic of converting the concrete values of a cuelang string to/from XML would be implemented in Go.

## Resources
* Specs: 
  * [XML Spec][xml-spec]
* Impl:
  * [Golang encoding/xml](https://golang.org/pkg/encoding/xml/)
  * [Go impl of XML-to-JSON converter](https://github.com/basgys/goxml2json)
* Other:
  * [Related Slack Thread](https://cuelang.slack.com/archives/CLT3ULF6C/p1585690861074400)

[xml-spec]: https://www.w3.org/TR/2008/REC-xml-20081126/

**Comment by mpvl** [comment]
It probably makes sense to take into account the proposal for new-style definition. Also the contemplated embedded scalar values (like top-level emit values but then for any struct) may provide a nice way to model XML attributes.  Also, I've been contemplating a guaranteed topological sort on fields that could be made possible by the new evaluator. This may help with field order and may also influence design decisions.

Taking these aspects into account might mean holding off on this design. It can also mean design XML in light of these features and helping to come up with possible requirements while this still can be influenced. This requires (a lot) more work, of course, but can be very beneficial.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/330.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
