### ISSUE TITLE
/pkg/crypto/ed25519 `Valid` support

### ISSUE THREAD

**Issue by rudolph9** [cuelang/cue#331]
## Summary

Support for validating ed25519 signatures. This would essentially map directly onto the golang [`ed25519.Verify`](https://godoc.org/crypto/ed25519#Verify) method. 

## Considerations
Support for an Ed25519 `Valid` builtin seems to fit well with the hermetic nature of cue and aligns well with the existing crypto packages md5, sha1, etc.

This request is intentionally very limited to NOT requesting support for `GenerateKey` or `Sign`.  1) managing private keys opens a lot of cans of worms and likely outside of the intended scope of cuelang.  2) GenerateKey is not idempotent (unless a seed is provided but again more cans or worms) and I can't remember off the top of my head if given the same `privateKey` and `message` if [`Sign`](https://godoc.org/crypto/ed25519#Sign) is idempotent but regardless; private keys and worms.

## Usage
example usage:
```
import "crypto/ed25519"

publicKey: bytes
message: bytes 
signature: bytes

isValid: ed25519.Verify(publicKey, message, signature)
```

## impl

Probably as simple as
```
package ed25519

import "crypto/ed25519"

func Valid(publicKey, message, signature []byte) bool {
	return ed25519(publicKey.(ed25519.PublicKey), message, signature)
}
```

**Comment by mpvl** [comment]
Seems reasonable.

**Comment by mpvl** [comment]
BTW, it is now considerably easier to add builtins.

**Comment by verdverm** [comment]
@mpvl can you elaborate on how to add builtins?

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/331.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
