### ISSUE TITLE
install issue - undefined: fVerbose

### ISSUE THREAD

**Issue by objectiveous** [cuelang/cue#34]
While running: 
`go get -u cuelang.org/go/cmd/cue`

I get: 
**cmd/cue/cmd/vet.go:66:7: undefined: fVerbose**

https://github.com/cuelang/cue/blob/master/cmd/cue/cmd/vet.go#L66

**Comment by mpvl** [comment]
Sorry about that. Fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/34.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
