### ISSUE TITLE
cue: support construction of cue structs and lists

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#343]
Currently there is no general way to use the cue package to create a struct or a list from `cue.Value` instances. `cue.Fill` can be used to create structs when the values are concrete, but doesn't work in general because it uses marshaling internally when the path is non-empty.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/343.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
