### ISSUE TITLE
pkg/list: list.Max sees empty list when unified with JSON on command line

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#345]
commit 6f37a71

The following testscript example fails:

```
stdin foo.json
exec cue vet x.cue json: -
-- foo.json --
{
    "ports": [
        2,
        5,
        7,
        2,
        76,
        98,
        3
    ],
    "newPort": 99
}
-- x.cue --
import "list"

ports: [... int]
newPort: list.Max(ports) + 1
```

The error is:

```
newPort: error in call to list.Max: empty list:
    ./x.cue:4:10
```

The list isn't empty, so this should not fail.

**Comment by mpvl** [comment]
This can be fixed by making JSON (and YAML) a first-class citizen in `cue/load`, which they should be.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/345.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
