### ISSUE TITLE
cmd/cue: cue import with pattern fails when other files are present

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#347]
commit 6f37a71e39b2c183c39875f2f442b8c8ae2b2526

The following testscript example fails - the `cue import` command does not import the `uni.yml` file.
When the unrelated `service.yaml` file is removed, it works OK.
I'd expect the `uni.yml` file to be imported regardless.

```
exec cue import -p uni --with-context -l 'filename' -n '.*uni.yml' ./...
cmpenv uni.cue expect-uni.cue
-- uni.yml --
hello: world
-- service.yaml --
x: foobie
-- expect-uni.cue --
package uni
"$WORK/uni.yml": hello: "world"
```

**Comment by mpvl** [comment]
cl pending.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/347.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
