### ISSUE TITLE
pkg/**: stdlib and builtin expansion

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#348]
Generally, we would like to see the standard library expanded.

At this point I am starting a conversation about the topic. We can change this header as things become better understood.

Thoughts:

- More functions from go-stdlib, these seem like low hanging fruit
- both pure / tools portions, how to separate (document this, where things belong), want to expand both most likely
- builtins for implementing structural func's
- builtins for things discussed around the evaluator rewrite and recursion
- external libs or packages, how do we decide what / when to bring in deps to cue?
- should we continue to generate the builtins as is today? or do we need to consider something that scales with the increased size of the stdlib?

Another thought is...

> Can we provided a way for users to register their own builtins?

iirc, the way builtins are happened, this might not be overly difficult. There is the issue (still to be created) that fields named the same as builtin funcs are sorted before other fields in a struct.

--- 

#### Functions and Packages:

From Go, for `pkg/tool`

- [ ] archive/*
- [ ] compress/*
- [ ] database (I can see people wanting to do something like an http call here)
- [ ] something like a file lock or concurrent access for commands
- [ ] more of / from os/*, net/*, file / filesystem / walktree
- [ ] something for logging
- [ ] support for readers / writers to chain other funcs and reduce overhead, something like Node/JS pipes
- [ ] better filesystem support, globs, in memory FS

From Go, for pure cue `pkg` expansion

- [ ] strings (not sure if there is a gap for this one and the next)
- [ ] strconv
- [ ] path.Join
- [ ] text/template (expose more of the interface, want to register partials for example)

External, for pure cue `pkg` expansion

- [ ] strings, some additions like Kace or a custom written version of the one or two missing funcs
- [ ] semver, as configurations are often dealing with these
- [ ] structural, object semantics based [diff,patch,merge,pick,filter]

Moonshot:

- [ ] access to cue runtime internals, like if I want to walk cue instances / values as defined in `cue.Value` rather than the exported / data forms.

I can see writing a cue tool which has a schema with it, and then processing local cue packages with the tool. So there may be a need to load and process other cue files from within the tool portion of a cue "program"

**Comment by apstndb** [comment]
I have noticed that to generate JWT in pure CUE is hard because there are no `crypto/rsa` package.
I requires `exec.Run` with sign helper command.
https://github.com/apstndb/cue-sandbox/blob/7d252af7b9f3665243fa319b54d5cbb3ebc68ebc/jwt/jwt.cue#L21-L33

**Comment by verdverm** [comment]
CUE is hermetic and I'm not sure secure crypto generation aligns with that goal

**Comment by apstndb** [comment]
Yeah, generally `crypto/rsa` is not hermetic but `SignPKCS1v15`(without blind signature) and `VerifyPKCS1v15` doesn't rely on RNG so they can be hermetic.
If they are supported, CUE can process JWTs.

**Comment by verdverm** [comment]
> SignPKCS1v15 (without RSA blinding) 

- The Go function takes a random reader, how do you propose getting around this?
- Does allowing this create weakened security for the sake of doing something with CUE?

**Comment by verdverm** [comment]
Of note, I just noticed tou are working in the non-hermetic area of the `cue` cli which has the tooling layer on top of CUE. So it could be feasible to add the crypto functions there, though I wonder how one might select a different source of randomness from outside of the go stdlib (i.e. something like Cloudflare using lava lamps)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/348.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
