### ISSUE TITLE
`(cue.opt).required = true` is ignored in encoding/protobuf

### ISSUE THREAD

**Issue by vvakame** [cuelang/cue#351]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.1.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

yes.

### What did you do?

I'm using `(cue.opt).required = true` in my .proto.

```
message FooBar {
  string id = 1 [
    (cue.opt).required = true
  ];
}
```

but its ignored in `encoding/protobuf`. I got `id?: string @protobuf(1)` in .cue file.

### What did you expect to see?

`id: string @protobuf(1)` . just without `?`

### What did you see instead?

`id?: string @protobuf(1)`

**Comment by vvakame** [comment]
https://github.com/cuelang/cue/blob/bcc19cee6187fb3f09248d3dd04439fe5eb80834/encoding/protobuf/parse.go#L759

`case "(cue_opt).required":` 🤔 
`case "(cue.opt).required":` 👍

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/351.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
