### ISSUE TITLE
cue/cue Golang API: Experience working with Cue in Golang

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#362]
**Is your feature request related to a problem? Please describe.**

When attempting to create Cue values from scratch in Golang, I found myself building up the AST by hand. There are some really nice methods there and it was easy to work with. However, it requires jumping between the `cue.Values(.*)` and the `ast.*` types. I'm not sure if the `cue.Value` lacks mutation/extension functions, if I can use the unify / slice functions to achieve what I'd like, or if the AST really is the appropriate way to do this.

**Describe the solution you'd like**

I need to understand more about the current design and experiment with the use case more before proposing a change.

**Describe alternatives you've considered**

Working with the AST and writing conversion helpers to switch between `cue.Value(.*)` and `ast.*`

**Additional context**

_note to self, add link to sample code showing what I am doing today_

---

Related to #348 #350

**Comment by errordeveloper** [comment]
I wasn't able to figure out how to construct a value, but I also ended-up without having to do it. At once I used a `map[string]interface{}` and passing it to `Fill` method.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/362.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
