### ISSUE TITLE
Injection doesn't work with imports

### ISSUE THREAD

**Issue by philipdexter** [cuelang/cue#365]
### What version of CUE are you using (`cue version`)?

commit #1370f0a

### Does this issue reproduce with the latest release?

yes

### What did you do?

Had a library with some `@tag(hi)` attribute, then ran `cue eval --inject hi=hi`.

### What did you expect to see?

The value "hi" to be injected.

### What did you see instead?

The value "hi" was not injected.

**Comment by mpvl** [comment]
Yes, this is deliberate. It seems to be poor practice to carry over injection across imports.

Do you have a good use case for it?

**Comment by philipdexter** [comment]
That sounds good. I don't have any use cases.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/365.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
