### ISSUE TITLE
Is there a way to ensure the lengths of two list arguments match?

### ISSUE THREAD

**Issue by riceluxs1t** [cuelang/cue#381]
Foo :: {
    l1: [...string]
    l2: [...string]
}

I want to make sure that instances of Foo have equal numbers of strings specified for l1 and l2. Is this possible to express in cuelang?

**Comment by verdverm** [comment]
We generally answer questions in Slack. You can join from this link: https://cuelang.org/community

You can with an extra field:

```
ex: {
  l1: [...string]
  l2: [...string]
  sameLength: len(l1) == len(l2)
}
```

**Comment by myitcv** [comment]
@verdverm the check field should really be a definition to avoid it being emitted:

```
ex: {
	l1: [...string]
	l1: ["test"]
	l2: [...string]
	l2: ["test"]
	sameLength :: len(l1) == len(l2)
	sameLength :: true
}
```

**Comment by myitcv** [comment]
I'll close this issue because we've address the direct question. There is also plans for a `constrain()` built-in as part of the evaluator redesign in #338

**Comment by verdverm** [comment]
@myitcv would hidden fields work equally as well?

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/381.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
