### ISSUE TITLE
Error w/master and cue dump (kubernetes example to YAML)

### ISSUE THREAD

**Issue by ekarlso** [cuelang/cue#383]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
99117ba9aca3ac260da6564209ac6dec9ad07e1c
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
```
https://github.com/ekarlso/cue-testing
cd cue-test
cue dump
```

0.1.2 worked for this.

### What did you expect to see?

YAML in a kubernetes compatible format

### What did you see instead?
```
../../cue/main dump
expected label or ':', found 'IDENT' dump (and 1 more errors)
```

**Comment by mpvl** [comment]
Your dump tool uses old-style space-separated labels that have been deprecated a long time ago and are now no longer supported.

The question is whether v0.1.2 didn't give a deprecation notice and why the error here doesn't produce line number information. That will need to be fixed.

**Comment by mpvl** [comment]
So to fix your problem, you'll need to write `a b: c` as `a: b: c`

**Comment by myitcv** [comment]
@ekarlso 

> Your dump tool uses old-style space-separated labels that have been deprecated a long time ago and are now no longer supported.

Please can you let us know if there is current documentation that refers to using space-separated labels?

**Comment by ekarlso** [comment]
Ah yes I had what @mpvl said!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/383.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
