### ISSUE TITLE
encoding/jsonschema: create definitions for all nested schemas

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#390]
**Is your feature request related to a problem? Please describe.**

Per discussion with @mpvl. cc @proppy given our previous exchange on this topic.

As part of 65163a0036b835cd6aa8894f1e91732ba85e99cd we flipped to use CUE for this repository's GitHub Actions Workflow specifications. As you can see from that commit, this change relies on the [GitHub-defined workflow JSON schema](https://github.com/SchemaStore/schemastore/blob/f7a0789ccb3bd74a720ddbd6691d60fd9e2d8b7a/src/schemas/json/github-workflow.json).

Within this schema is a `"jobs"` field of type struct that is defined using [`patternProperties`](https://github.com/SchemaStore/schemastore/blob/f7a0789ccb3bd74a720ddbd6691d60fd9e2d8b7a/src/schemas/json/github-workflow.json#L826-L831):

```
...
    "jobs": {
      "$comment": "https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobs",
      "description": "A workflow run is made up of one or more jobs. Jobs run in parallel by default. To run jobs sequentially, you can define dependencies on other jobs using the jobs.<job_id>.needs keyword.\nEach job runs in a fresh instance of the virtual environment specified by runs-on.\nYou can run an unlimited number of jobs as long as you are within the workflow usage limits. For more information, see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits.",
      "type": "object",
      "patternProperties": {
        "^[_a-zA-Z][a-zA-Z0-9_-]*$": {
...
```

This gets translated to:

https://github.com/cuelang/cue/blob/8fcefc84bf1d6868608beb7680a916f57181d9ed/cue.mod/pkg/github.com/SchemaStore/schemastore/schemas/json/github-workflow.cue#L306-L307

The issue is that it is now very tricky to refer to the schema that defines the value that can appear in fields in this `"jobs"` struct:

```
package x

import "github.com/SchemaStore/schemastore/schemas/json"

#job: (json.Workflow.jobs & {x: _}).x
#step: ((#job & {steps: _}).steps & [_])[0]

myJob: #job & {
	name: "myJob"
	"runs-on": "ubuntu-latest"
}

myStep: #step & {
	name: "myStep"
	if: "ok"
}
```

Full repro:

https://gist.github.com/myitcv/4ef3d99aea77882ac460e3aaf76622c3

Output is:

```
> exec cue eval -c .
[stdout]
myJob: {
    name:      "myJob"
    "runs-on": "ubuntu-latest"
}
myStep: {
    name: "myStep"
    if:   "ok"
}
```

**Describe the solution you'd like**

Something that looks like this:

```
package x

import "github.com/SchemaStore/schemastore/schemas/json"

myJob: json.Workflow.jobs.#job & {
	name: "myJob"
	"runs-on": "ubuntu-latest"
}

myStep: json.Workflow.jobs.#job.steps.#step & {
	name: "myStep"
	if: "ok"
}
```

i.e. the schemas used within `jobs` and `steps` to be defined inline, and easily reference-able.

**Describe alternatives you've considered**

There is a workaround... but it's not pretty :)

**Additional context**

n/a

**Comment by proppy** [comment]
In:
```
json.Workflow.jobs.#job
```
Where would the #job comes from? (since it wouldn't be defined in the underlying jsonschema).

I wonder if `[]`, `[...] or even `[_]` would be acceptable as a way to express querying on any valid field of a srruct/list without causing clash for other syntax?
```
myStep: json.Workflow.jobs.[].steps.[] & { }

```

**Comment by myitcv** [comment]
> Where would the #job comes from? (since it wouldn't be defined in the underlying jsonschema).

It was just a very loose idea to illustrate that we need to be able to address these schemas/constraints in some way.

@rogpeppe also pointed out that we should be able to address the field name constraint too, i.e.:

```
=~"^[_a-zA-Z][a-zA-Z0-9_-]*$" & !~"^()$"
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/390.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
