### ISSUE TITLE
Semver as a basic type like number or string

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#407]
Configuration is often dealing with versions and there is not an easy way to compare version identifiers during validation and evaluation.

Having a `semver` basic type (not sure the right term here) like `number` and `string`.

```
schema: {
  version: semver
}

foo: schema & {
  version: v0.3.4
}

range: {
  version: >v0.3.0 & < v1.0.0
}

fail: {
   version: >v0.4.0
}

ex1: foo & range // => foo
ex2: foo & config // => _|_
```

This seems like a good library to use: https://pkg.go.dev/golang.org/x/mod@v0.3.0/semver

**Comment by rvadhavk** [comment]
I don't think this should be a bulitin.  It'd be better to have a generic method of creating user-defined types with these semantics.  Like maybe define the comparison operator on lists be a lexicographic ordering.

**Comment by rvadhavk** [comment]
Another similar problem is expressing date and time ranges, which I don't think is currently possible in cue (unless you just using unix epoch seconds or something).

**Comment by verdverm** [comment]
I think you are right, so I'll update this to be semver as a built in package in Cue.

See the 'pkg/**' packages available. There are things for dates, ips, and more.  Semver comparison can likely fit here via functions.

I'm not sure there is a path for user defined types which can be used in builin operations like < and other Boolean ops. @mpvl ?

**Comment by myitcv** [comment]
The simplicity of not allowing re-definition of `<` and friends is, I think, a massive benefit that outweighs the cost of complexity, readability that allowing it would introduce. 

Instead, this situation (and many others) sound like a use case for the previously proposed `constrain()` build in.

**Comment by mpvl** [comment]
@rvadhavk: time.Time enforces a proper string type and you can just use string comparison for ordering. There is no need to redefine `<`, it is just regular string ordering.

Semver can easily be expressed as a fairly simple regexp. The only thing I can imagine that would be useful is numeric sorting (e.g. using x/text/collate). Again, this can be solved with a more generic package. I don't think it warrants a builtin package. It can easily be provided as a native CUE package externally. I don't think semver is at the same level of standardization as ip or dates.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/407.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
