### ISSUE TITLE
cue: disjunctions not handled correctly in list ellipsis

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#419]
```
#A: {
	a: string
}

#B: {
	_b: string
}

#X: #A | #B

l: [...#X]

l: [
	{_b: "bar"}
]
```

```
 cue export test.cue
l.0: cannot convert incomplete value "(C{a: string, _b: \"bar\"} | C{_b: (string & \"bar\")})" to JSON:
    ./test.cue:1:5
    ./test.cue:11:8
    ./test.cue:14:2
```

```
#B: {
	_b: string
}

l: [...#B]

l: [
	{_b: "bar"}
]
```

```
 cue export test.cue
{
    "l": [
        {}
    ]
}
```

_Originally posted by @eonpatapon in https://github.com/cuelang/cue/discussions/417_

**Comment by mpvl** [comment]
This is already fixed in the new evaluator.

**Comment by mpvl** [comment]
See https://github.com/cuelang/cue/blob/master/cue/testdata/definitions/issue419.txtar

**Comment by mpvl** [comment]
Actually, the original was correct. `_b` is a hidden field and is not included in the closedness checking, as per the spec.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/419.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
