### ISSUE TITLE
Cue Scripting : Simple Makefile equivalent example?

### ISSUE THREAD

**Issue by StevenACoffman** [cuelang/cue#428]
**Is your feature request related to a problem? Please describe.**
I have used [Nix to build docker images](https://github.com/Xe/site/blob/master/docker.nix) but I'm not sure how to use Cue in a similar way. The tutorial shows how to use Cue for Kubernetes, but I'm curious if I can use it for the step before.

**Describe the solution you'd like**
I would like a small example documented. 

**Describe alternatives you've considered**
Perhaps Cue's scope is currently too limited to achieve this?

**Comment by verdverm** [comment]
Do you mean build Cue as a binary from source?

What is the step before Kubernetes?

**Comment by StevenACoffman** [comment]
Specifically, an example demonstrating building a docker image using Cue via the scripting layer.

Typically, at my work the desired sequence is:

1. we start from a git repository of source code at a particular git SHA1 commit
2. build docker image from it
3. tag the image with the git SHA1
4. push the image tag to a docker registry (like GCS)
5. update the kubernetes manifests to reference the new image tag (git SHA1)
6. apply the kubernetes manifests

I can perform that same sequence from Bash, Go, Makefile, or Nix scripts. I think it's possible to do this with Cue scripts, but I'm not clear on how and would appreciate an example or guidance on where to look.

**Comment by verdverm** [comment]
Assuming you aren't looking to assemble dockerfiles from more abstract Cue designs, and are mainly looking for more complex examples for the tooling layer, check out https://github.com/hofstadter-io/jumpfiles  At this point I'm not really looking to use the scripting layer. I'd rather write Go.

I'm actually working on a new scripting lang & shell. I want the ease of bash for working with arbitrary "stuff," and the abilities we typically have to go to a real language for without needing to.

**Comment by mpvl** [comment]
It should definitely be possible to use CUE for Docker images by using the "exec" task type to shell out to the docker binary.

The disadvantage of using Go is that it is hard to reuse workflows, whereas this is easier with CUE.

**Comment by verdverm** [comment]
Yeah, I do this with other tools like this:

- https://github.com/hofstadter-io/jumpfiles/blob/master/lib/devenv_tool.cue
- https://github.com/hofstadter-io/jumpfiles/blob/master/lib/config.cue#L67
- https://github.com/hofstadter-io/jumpfiles/blob/master/lib/grid.cue#L66
- https://github.com/hofstadter-io/jumpfiles/blob/master/lib/k8s/gke.cue

I'm liking my Cue design, Go runtime experiment because the attributes are freaking sweet!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/428.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
