### ISSUE TITLE
Cue hanging when a empty '-' file is in the scope

### ISSUE THREAD

**Issue by b4nst** [cuelang/cue#442]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version devel darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```shell
mkdir __442 & cd __442
touch -
cue eval
```

### What did you expect to see?
`no CUE files in .` or something like that

### What did you see instead?
Cue hanging indefinitely

**Comment by verdverm** [comment]
I wonder if that filename looks like stdin? Will have to look deeper in the code, probably starting around the load dir

**Comment by mpvl** [comment]
@verdverm: that is very likely the cause indeed.

Not sure what to do about it. Probably add a check to test if a file named `-` exists when stdin input is requested and warn the user about it.

**Comment by mpvl** [comment]
Fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/442.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
