### ISSUE TITLE
confusing error: build constraints exclude all CUE files

### ISSUE THREAD

**Issue by errordeveloper** [cuelang/cue#453]
I have noticed `build constraints exclude all CUE files` error a few times, seems like it occurs when file name doesn't match package name or the name of parent directory - I'm still not sure... but I looks quite confusing, as there is no notion of "build constraints" that is visible to the user at the moment.

**Comment by mpvl** [comment]
This was fixed with https://github.com/cuelang/cue/commit/1f1c3f6ed4604516667e53daf867aebe0eb97563.

This error now list the excluded files, along with a reason for their exclusion.

**Comment by errordeveloper** [comment]
thanks @mpvl!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/453.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
