### ISSUE TITLE
Add downcasts

### ISSUE THREAD

**Issue by zombiezen** [cuelang/cue#454]
**Is your feature request related to a problem? Please describe.**
I have a configuration where I have a struct containing a mapping that is frequently edited. Different declarations across my mapping require different subsets of that mapping inside their struct, but frequently not the whole thing. 

In this same configuration, I sometimes use template-like objects that have definitions and I want to convert them to a more basic type without the definitions. For example:

```
#Object: {
  name: string
}

#MyTemplate: {
  #foo: string
  name: "foo-\(#foo)"
}

// ERROR: does not unify
#Object & {
  #MyTemplate
  #foo: "bar"
}
```

In both cases, I have to write a rather verbose and hard-to-understand comprehension to get the desired effect:

```
#Object & {
  let #expanded = {
    #MyTemplate
    #foo: "bar"
  }
  for k,_ in #Object { "\(k)": #expanded[k] }
}
```

**Describe the solution you'd like**

I'd like a kind of "downcasting" conversion that removes any fields in a struct that aren't in another struct. I don't have an informed opinion about syntax, but borrowing from Go's type conversion syntax, something like:

```
#Object & #Object({
  #MyTemplate
  #foo: "bar"
})
```

**Describe alternatives you've considered**

As mentioned above, this is possible in the language already using comprehensions, but is not obvious to those who haven't already dived deep into CUE what this is doing. A lack of user-defined functions makes it difficult to abstract the operation, thus bringing me to ask for language support. I could do something like (untested):

```
#Downcast: {
  #value: {...}
  #type: {...}
  #output: { for k,_ in #type { "\(k)": #value[k] } }
}

#Object & #Downcast{
  #value: {
    #MyTemplate
    #foo: "bar"
  }
  #type: #Object
}.#output
```

But this doesn't add terribly much clarity IMO, it just adds indirection.

**Comment by zombiezen** [comment]
I just realized that the downcasting should probably imply unifying with its value, so my desired solution would actually look like:

```
#Object({
  #MyTemplate
  #foo: "bar"
})
```

**Comment by proppy** [comment]
I wonder if having a binary operators like Python has for sets:
- `&` for interestion
- `-` for difference
- `^` for symetic difference
- `<` subset test
- `>` superset test
could be a different take to this issue?

@jlongtine pointed me to a recent discussion https://cuelang.slack.com/archives/CLT3ULF6C/p1599911085226700?thread_ts=1599910691.226200&cid=CLT3ULF6C which discuss a similar `%` operator.

It could user to keep the same mental model they have about unification (and other binary operator):
```
#Object % {
  #MyTemplate
  #foo: "bar"
}
```
While allowing easier chaining:
```
#Object % {
  #MyTemplate
  #foo: "bar"
} % {
  #MyTemplate
  #foo: "bar"
}
```

**Comment by mpvl** [comment]
@proppy : I think having full set logic is entering scary territory. Perhaps in a struct package.

@zombiezen : a problem with the `T(V)` notation is that it doesn't jive well with the builtin syntax and possible functional interpretation of structs that can be a result of generalizing struct.  I wasn't able to come up with something better.

One thought I had though: the plan is to expand the selection operator to allow more types to both facility the query mechanism and label mechanism:

```
[pattern]: T // Apply T to fields matching pattern (already exists, but the pattern can match more)
(value): T   // create field label from dynamic value.
```
then the idea was to allow the following corresponding RHS selectors
```
a.[pattern]
a.(value)
```
These could be used wherever comprehensions are used now (they create streams). Not that this makes the `a[x]`operator somewhat redundant.

It is possibly problematic, but one idea would be to overload `a.(value)`. That is, for concrete scalars it looks up a field, but for structs and lists, `a.(T)` would projects the streamed values of `a` onto `T`, discarding any field or element that does not exist in `T`. This can arguably be sold as a natural extension of the selection mechanism.

Coincidentally, it is also very close in syntax to Go's dynamic cast operator.

Anyway, just brainstorming here. I'm not sure if this actually would make sense logically. But it seems more feasible than `T(a)` at least.

For completeness of the whole query extension direction: the idea of the pattern selection operator would be allowed to be of the form `[fieldPattern: T]`, either LHS or as RHS selector, where fields are matched as usual, and values of this field are further matched by T. There is more but this is probably already enough context.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/454.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
