### ISSUE TITLE
confusing error: field "foo" is optional

### ISSUE THREAD

**Issue by errordeveloper** [cuelang/cue#455]
When optional field is reference, the error that comes is `field "foo" is optional`, that's just too confusing. It would be much more helpful that `field "foo" is optional and cannot be referenced in <specific case>` or something just a bit more specific than what it currently is.

**Comment by errordeveloper** [comment]
Thanks a lot for addressing this!!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/455.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
