### ISSUE TITLE
VSCode Extension to Preview Configuration Output (json/yaml)

### ISSUE THREAD

**Issue by hongchaodeng** [cuelang/cue#456]
**Describe the solution you'd like**
As a user writes cue code, he can preview the output json/yaml in flight in VSCode. Similar to markdown preview feature.

I'm wondering if there is any plan for it?

**Comment by hongchaodeng** [comment]
Similar to https://github.com/heptio/vscode-jsonnet

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/456.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
