### ISSUE TITLE
default value + unification breaks `if`

### ISSUE THREAD

**Issue by shykes** [cuelang/cue#459]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.2.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```
$ cat <<EOF | cue  export -
#Good : {
    activate: bool | *false

    if activate {
        status: "activate = true"
    }
	if !activate {
		status: "activate = false"
	}
}
#Bad: _ & #Good

good: #Good & { activate: true }
bad: #Bad & { activate: true }
EOF
```

### What did you expect to see?

```
{
    "good": {
        "status": "activate = true",
        "activate": true
    },
    "bad": {
        "status": "activate = true",
        "activate": true
    }
}
```

### What did you see instead?

```
{
    "good": {
        "status": "activate = true",
        "activate": true
    },
    "bad": {
        "status": "activate = false",
        "activate": true
    }
}
```

**Comment by shykes** [comment]
It looks like this issue is a dupicate of #436 .

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/459.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
