### ISSUE TITLE
Obscure error message with master

### ISSUE THREAD

**Issue by ekarlso** [cuelang/cue#465]
### What version of CUE are you using (`cue version`)?
304b02e / 0.3 alpha / trunk + fix for #458

### Does this issue reproduce with the latest release?
yes

### What did you do?
```
cm_token_secret: string | *_|_

if cm_token_secret != "" {
```

```
cue eval
```

### What did you expect to see?
Error that gives meaning

### What did you see instead?
```incomplete```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/465.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
