### ISSUE TITLE
cmd/cue: yaml.Marshal fails on #: "working-directory" in command definition

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#476]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +304b02e linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
-- x_tool.cue --
package x

import (
        "tool/cli"
        "encoding/yaml"
)

command: dostuff: {
        write: cli.Print & {
                text: "yaml is " + yaml.Marshal(w)
        }
}

command: dostuffloop: {
        for w in l {
                write: cli.Print & {
                        text: "yaml is " + yaml.Marshal(w)
                }
        }
}
-- y.cue --
package x

#Workflow: {
        #: "working-directory": string
}

l: [w]
w: #Workflow & {
}
```

Notice how the following succeeds:

```
$ cue cmd dostuffloop
yaml is {}

```

But the following fails:

```
$ cue cmd dostuff
command.dostuff: field `"working-directory"` not allowed
```

### What did you expect to see?

Success in both situations. 

### What did you see instead?

As above.

**Comment by myitcv** [comment]
Just to add that both commands work with `v0.2.2`

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/476.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
