### ISSUE TITLE
cmd/cue: cmd does not report superfluous imports in _tool.cue files

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#477]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +304b02e linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
-- x_tool.cue --
package x

import (
        "strings"
        "tool/cli"
)

command: print: cli.Print & {
        text: "this is a test"
}
```

```
cue cmd print
```

### What did you expect to see?

An error:

```
imported and not used: "strings":
```

(which I do see with `v0.2.2`)

### What did you see instead?

The printed output:

```
this is a test
```

**Comment by mpvl** [comment]
This is now fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/477.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
