### ISSUE TITLE
cmd/cue: fmt causes comments to jump around

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#478]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +304b02e linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cp x.cue x.cue.golden
exec cue fmt x.cue
cmp x.cue x.cue.golden

-- x.cue --
package x

example: {
	// This is a comment

	// Another comment
	something: {
		else: 5
	}
}
```

### What did you expect to see?

Success.

### What did you see instead?

Failure.

**Comment by mpvl** [comment]
Analysis: this turns out to be a parser issue, which attaches the comment incorrectly.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/478.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
