### ISSUE TITLE
Convert booleans in string interpolations

### ISSUE THREAD

**Issue by kumorid** [cuelang/cue#492]
**Is your feature request related to a problem? Please describe.**

I often need to convert boolean values to be placed into text files (scripts, configs for programs) ... and cannot resort to a straightforward string interpolation.

String interpolation already converts scalar numeric values to string before inserting them. Boolean values, however, are not converted. This seems a bit uneven, as boolean values have a precise representation in json: `true` or `false` and it would make interpolating values much more consistent (and practical)

Having this implemented would make interpolating any scalar value consistent. 
In the future, more consistence could be gained by actually converting any concrete value to json... (Not part of this request though).

**Describe the solution you'd like**

<pre>
--- in/test.cue ---
#mybool: true

a: " \(#mybool) interpolation"

--- out/export
{
   "a": "true interpolation"
}
</pre>

**Describe alternatives you've considered**

The alternative is to use package "strconv.FomratBool", which would produce exactly the same result (no way of adding extra formatting instructions). 

But, as hinted above: it begs the question of why numbers are treated as special scalars.

**Additional context**

**Comment by mpvl** [comment]
Fixed by 30ca0629cdcc2668bb2972691609300db2b3a52a. (Wrong issue number in commit message so wasn't closed automatically.)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/492.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
