### ISSUE TITLE
doc: tutorial types errors, float not recognized

### ISSUE THREAD

**Issue by ghchinoy** [cuelang/cue#50]
Using `types.cue` from https://github.com/cuelang/cue/blob/master/doc/tutorial/basics/types.md errors on running `cue eval`.

```
$ cue eval -i types.cue 
--- .
unsupported op &((float)*, int):
    ./types.cue:2:8
    ./types.cue:7:10
    
// /home/ghchinoy/dev/cueexperments
{
    point: {
        x:  float
        y:  float
    }
    xaxis: {
        x:  _|_ // unsupported op &((float)*, int)
        y:  float
    }
    yaxis: {
        x:  float
        y:  _|_ // unsupported op &((float)*, int)
    }
    origin: {
        x:  _|_ // unsupported op &((float)*, int)
        y:  _|_ // unsupported op &((float)*, int)
    }
}```

**Comment by mpvl** [comment]
Ah,  there was a recent change to make integer literals not floats. I’ll update the example to use number, the now recommended type to use. 

I’m close to finishing some tests for the tutorials to allow catching these kind of things during development.

**Comment by ghchinoy** [comment]
Thanks @mpvl  - please let me know if there's anything I can do to help!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/50.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
