### ISSUE TITLE
pkg/strings: regression: strings.Join fails with new evaluator

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#500]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +c6ade67 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval
-- x.cue --
package x

import "strings"

x: strings.Join(strings.Split("test", "")[1:], "")
```

### What did you expect to see?

```
x: "est"
```

(per v0.2.2)

### What did you see instead?

```
error in call to strings.Join: not properly initialized (state: 0, value: *adt.ListMarker)
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/500.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
