### ISSUE TITLE
Allow URL of a file in the `vet` command

### ISSUE THREAD

**Issue by anik120** [cuelang/cue#505]
Hi guys, 

It'd be nice to have a way to include the URL of a file in the `vet` command so that users don't have to always clone the repo containing the cue file if they just want to validate their json/yaml against the cue file. 

I.e 
Current implementation: 

``` $ cue vet --help 
vet validates CUE and other data files
.
.
.
Examples:

  # Check files against a CUE file:
  cue vet foo.yaml foo.cue

  # Check files against a particular expression
  cue vet translations/*.yaml foo.cue -e Translation
```

Requested implementation: 

``` $ cue vet --help 
vet validates CUE and other data files
.
.
.
Examples:

  # Check files against a CUE file:
  cue vet foo.yaml foo.cue

 # Check files against a CUE file hosted on a server: 
 cue vet https://github.com/project-name/definition.cue myfile.json

  # Check files against a particular expression
  cue vet translations/*.yaml foo.cue -e Translation
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/505.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
