### ISSUE TITLE
cmd/cue: importing still uses old-style YAML

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#512]
commit c6ade67b538f585a309c52d271b17119cf18f98b

```
% cat x.yml
foo:
  - x
  - y
% 
% cue import x.yml
% cat x.cue
foo: [
	"x",
	true,
]
```

The `y` should encode as the string `"y"` not the boolean `true`.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/512.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
