### ISSUE TITLE
cmd/cue: yaml import fails on string containing zero code point

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#514]
commit 456108de1c31cd5c61045ec20832c3723f2ae9b2

The following YAML fails on import:

```
b: "\0"
```

The error message is:
```
b: invalid string: invalid syntax:
    ./y.yaml:1:5
```

The syntax appears correct, and 0 is a valid Unicode code point, so this should be OK.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/514.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
