### ISSUE TITLE
spec: close() incorrectly specified as working recursively

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#531]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +e3a03a1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
package x

#Configuration: {
	configurations: [string]: string
	...
}

#A1Config: #Configuration & close({
	configurations: {
		a: string
	}
})

#A2Config: #Configuration & close({
	configurations: close({
		a: string
	})
})

#A3Config: #Configuration & #A3ConfigStructure

#A3ConfigStructure: {
	configurations: {
		a: string
	}
}

a1: #A1Config & {
	configurations: {
		a: "hello"
		b: "hello"
	}
}

a2: #A2Config & {
	configurations: {
		a: "hello"
		b: "hello"
	}
}

a3: #A3Config & {
	configurations: {
		a: "hello"
		b: "hello"
	}
}
```

### What did you expect to see?

```
a1.configurations: field `b` not allowed:
...
a2.configurations: field `b` not allowed:
...
a3.configurations: field `b` not allowed:
...
```

### What did you see instead?

```
a2.configurations: field `b` not allowed:
...
a3.configurations: field `b` not allowed:
...
```

Credit to @rogpeppe for working this out

**Comment by myitcv** [comment]
This actually a spec issue per @mpvl. Retitled

**Comment by mpvl** [comment]
This have been updated in the spec.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/531.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
