### ISSUE TITLE
Hidden definitions are not proper definitions (not closed)

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#533]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +e3a03a1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval

-- x.cue --
package x

#x: {
	Name: string
}

_#x: {
	Name: string
}

x1: #x & {
	Name: "hello"
	Age:  50
}

x2: _#x & {
	Name: "hello"
	Age:  50
}
```

### What did you expect to see?

```
x1: field `Age` not allowed:
x2: field `Age` not allowed:
```

### What did you see instead?

```
x1: field `Age` not allowed:
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/533.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
