### ISSUE TITLE
Allow setting working directory for exec.Run

### ISSUE THREAD

**Issue by roman-mazur** [cuelang/cue#536]
`exec.Run` does not seem to have a way to change the working directory atm.
Should be simple enough to implement if we add a field that will map to `exec.Cmd.Dir` in Go.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/536.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
