### ISSUE TITLE
cmd/cue: cue import unnecesarily escapes double quotes in multiline strings

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#541]
commit ff306b79708eee06adaa73e6fb62449278727101

Running `cue import` on the following JSON produces CUE output that escapes the double-quotes even though there's no need to escape them unless there are three in a row:

```
{
	"x": "foo \n\"bar\""
}
```

This produces:

```
x: """
        foo 
        \"bar\"
        """
```

I'd expect to see:

```
x: """
        foo 
        "bar"
        """
```

**Comment by myitcv** [comment]
See also https://github.com/cuelang/cue/issues/389

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/541.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
