### ISSUE TITLE
cmd/cue: commands much slower with v0.3.0-alpha series

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#547]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +65468d5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Start with the following txtar archive: https://gist.github.com/myitcv/f805977b39384416a374d3c4e5a9f6e3

Then simply time `cue def` using `v0.2.2` and `65468d5`. Locally I see:

```
# v0.2.2
$ cue def
...
real    0m0.117s
user    0m0.179s
sys     0m0.008s
```

```
# +65468d5
$ cue def
...
real    0m1.536s
user    0m2.887s
sys     0m0.192s
```

### What did you expect to see?

Similar or better times with the v0.3.0 series.

### What did you see instead?

As above.

**Comment by myitcv** [comment]
As I mentioned offline, please let me know if there is anything I can sensibly/feasibly do to help reduce this down.

**Comment by mpvl** [comment]
Analysis. New evaluator seems to produce 20x the amount of memory. This is partly to be expected: each node now has quite a bulky bookkeeping node that is created for each node. These do not need to be kept, though. The idea was to have a MemPool of sorts to reuse them (including all the generated slices), but this has not been done yet.

**Comment by leoluk** [comment]
Same issue here - new evaluator is painfully slow on a medium-sized code base, preventing us from using it.

```
$ cue def | wc -l 
1183

# 94db2eb171e7934e5d773d275bfe0d7558333c56 (v0.2.2)
$ time cue def > ~/1

real	0m1.135s
user	0m2.888s

# cefe38b12bc4df48f5bc100d0a45fc9ec563e36d (v0.3.0-alpha6)
$ time cue def > ~/2

real	0m6.853s
user	0m18.401s

**Comment by leoluk** [comment]
A quick investigation with pprof (using the patch in #619) shows that much of that time is spent in GC:

![image](https://user-images.githubusercontent.com/859697/103086443-f0381780-45e4-11eb-92ff-2cc82cbe7ab7.png)

(repo contains private data - not sure if the raw pprof output is safe to share)

Accordingly, running with `GOGC=off` significantly improves performance:

```
$ time GOGC=off cue dump > /dev/null

real	0m3.465s
user	0m2.884s
sys	0m0.574s
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/547.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
