### ISSUE TITLE
Opening a struct with ... causes error

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#552]
### What version of CUE are you using (`cue version`)?

v0.3.0-alpha4

### Does this issue reproduce with the latest release?

Not with v0.2.2, working through issues migrating to v0.3.0-alpha*

### What did you do?

```
package mix

import "strings"

#Import: {
        As: string | *""
        Path: string
}

#Command: {
        Name: string
        cmdName: strings.ToCamel(Name)

        Hidden?: bool

        #Common

        // UNCOMMENT this to cause error
        // ...
}

#Common: {
        Name: string
        Usage: string | *Name
        Imports?: [...#Import]

        Topics: [string]: string

        Commands: [...#Command] | *[]
}
```

### What did you expect to see?

```
$ cue eval mix.cue 
import "strings"

#Import: {
    As:   ""
    Path: string
}
#Command: {
    Name:    string
    cmdName: strings.ToCamel(Name)
    Usage:   string
    Topics: {}
    Commands: []
}
#Common: {
    Name:  string
    Usage: string
    Topics: {}
    Commands: []
}
```

### What did you see instead?

```
$ cue eval mix.cue 
#Command: cannot mix bulk optional fields with dynamic fields, embeddings, or comprehensions within the same struct
```

**Comment by mpvl** [comment]
This is part of the set of restrictions to move from old CUE semantics to (more like) JSON schema semantics, but agreed that this particular restriction is a bit too stringent, especially considering that `...T` is not yet supported.

**Comment by verdverm** [comment]
So is it this line `Commands: [...#Command] | *[]` that is the `...T` which is not supported yet?

(and why I still see this error on tip?)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/552.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
