### ISSUE TITLE
encoding/openapi: support OpenAPI

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#56]
This is a tracking Issue for any OpenAPI changes until most of it is completed. This includes:

- Convert CUE to OpenAPI
- Convert OpenAPI to CUE

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/56.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
