### ISSUE TITLE
cmd/cue: unable to reference definition from package-embedded definition

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#564]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aee9955 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
-- cue.mod/module.cue --
module: "mod.com"
-- x.cue --
package x

import "mod.com/y"

y.#G

Ts: ["hello"]
x: #T
-- y/y.cue --
package y

#G: {
	Ts: [...string]
	#T: or(Ts)
}
```

Running:

```
$ cue def
x: reference "#T" not found:
    ./x.cue:8:4
```

Which makes sense because there is no `#T` in scope. 

To my knowledge there is no way of referring to the package instance in which `y.#G` is embedded. But that is the only way to correctly refer to `#T` (because `#T`, is defined in terms of the fields of `y.#G`)

Hence I think we need some way to refer to the "current" package instance.

**Comment by myitcv** [comment]
Noting a workaround per an offline conversation with @mpvl:

```
// x.cue
package x

import "mod.com/y"

y.#G

#T: _

Ts: ["hello"]
x: #T
```

Another idea we kicked around was using a bare `.` to mean "the current scope", enabling something like this:

```
// x.cue
package x

import "mod.com/y"

y.#G

Ts: ["hello"]
x: .#T
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/564.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
