### ISSUE TITLE
Subsume fails to match

### ISSUE THREAD

**Issue by shykes** [cuelang/cue#566]
NOTE: I don’t know if this is an actual issue with `Subsume` or if I’m using it wrong. I thought an issue with a repro case would be the most productive way to ask in either case.

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-alpha4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Latest alpha release.

### What did you do?

```
$ cat > main.go <<‘EOF’

package main

import (
        "fmt"
        "cuelang.org/go/cue"
        cueErrors "cuelang.org/go/cue/errors"
)

func main() {

        r := &cue.Runtime{}
        spec, err := r.Compile(`spec.cue`, `#Run: { action: "run", command: [...string] }`)
        if err != nil {
                panic(err)
        }
        runSpec := spec.LookupDef("#Run")
        if err := runSpec.Err(); err != nil {
                panic(err)
        }
        config, err := r.Compile(`value.cue`, `{ action: "run", command: ["echo", "hello"] }`)
        if err != nil {
                panic(err)
        }
        v := config.Value()
        if err := v.Validate(); err != nil {
                panic(err)
        }
        if err := runSpec.Subsume(v); err == nil {
                fmt.Println("MATCH")
        } else {
                fmt.Printf("NO MATCH: %s\n", err)
        }
        if err := runSpec.Subsume(v, cue.Final()); err == nil {
                fmt.Println("(final) MATCH")
        } else {
                fmt.Printf("(final) NO MATCH: %s\n", cueErrors.Details(err, &cueErrors.Config{}))
        }
}
EOF
```

```
$ go run main.go
```

### What did you expect to see?

```
MATCH
(final) MATCH
```

### What did you see instead?

```

$ go run main.go 
NO MATCH: value not an instance
(final) NO MATCH: field command not not present in {action:"run",command:["echo","hello"]}
missing field "command"
```

**Comment by shykes** [comment]
Updated my example to include `cue.Final()`

**Comment by myitcv** [comment]
I think you actually want to be using `Value.Unify()` and `Value.Validate()` here. So something like:

```
package main

import (
	"fmt"

	"cuelang.org/go/cue"
)

func main() {

	r := &cue.Runtime{}
	spec, err := r.Compile(`spec.cue`, `#Run: { action: "run", command: [...string] }`)
	if err != nil {
		panic(err)
	}
	runSpec := spec.LookupDef("#Run")
	if err := runSpec.Err(); err != nil {
		panic(err)
	}
	config, err := r.Compile(`value.cue`, `{ action: "run", command: ["echo", "hello"] }`)
	if err != nil {
		panic(err)
	}
	v := config.Value()
	if err := v.Validate(); err != nil {
		panic(err)
	}
	res := runSpec.Unify(v)

	if err := res.Validate(cue.Final(), cue.Concrete(true)); err == nil {
		fmt.Println("MATCH")
	} else {
		fmt.Printf("NO MATCH: %s\n", err)
	}
}
```

`Value.Subsume()` is more geared towards determining (API) compatibility of either schemas or data.

**Comment by verdverm** [comment]
When using `Unify` do you want an extra `res.Err() != nil` check before the `res.Validate()`?

**Comment by shykes** [comment]
That makes sense. I will try it right away. Thank you!

**Comment by myitcv** [comment]
@verdverm 

> When using `Unify` do you want an extra `res.Err() != nil` check before the `res.Validate()`?

Shouldn't be necessary; the `Validate()` is essentially a finer grained way of checking the state of `res`. It being in an error is an error in and of itself.

**Comment by myitcv** [comment]
Note: there appears to be a bug in `tip` (`v0.3.0-alpha4.0.20201022063748-aee9955c790b`) which affects my solution: https://github.com/cuelang/cue/issues/567

**Comment by mpvl** [comment]
There is definitely a bug. I've identified what is going wrong, I just don't know exactly yet why it happens. It is definitely API related, though, and would not typically occur during normal CUE evaluation, other than perhaps a builtin that uses the CUE API and is running into the same issue.

**Comment by mpvl** [comment]
I have found the bug and am cleaning up some related issues with subsume.

Note that the correct answer is probably to not match when not using Final, and only to match when using Final.

The reason is that in your example, the subsuming struct is closed, whereas the subsumed struct is open, and thus defines a larger space of values. Maybe it should also pass in default mode, but that doesn't seem right.

**Comment by mpvl** [comment]
So in v0.2 it used to match either way, though. So I'll adopt these semantics.

**Comment by shykes** [comment]
@myitcv an update, your approach has worked well for me so far, EXCEPT that an empty value always matches everything... I’m not sure if that is normal, or a bug. And either way how to resolve it?

**Comment by verdverm** [comment]
What do you mean by empty value?

I'd expect `_` to unify with anything and an open struct `{}` to unify with all other structs.

An edge case could be to check if a structs length is zero https://pkg.go.dev/cuelang.org/go@v0.3.0-alpha6/cue#Struct.Len

**Comment by shykes** [comment]
Yes I meant an empty struct. And I just implemented a check for struct length zero :) But wasn’t sure whether to think of that as a temporary workaround, or a reliable solution.

Thanks for the prompt reply!

**Comment by verdverm** [comment]
When a Close function makes it into the API, you could call that on the value before Unify()

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/566.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
