### ISSUE TITLE
Support for not() builtin

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#571]
Noting an offline conversation with @mpvl and @rogpeppe 

**Is your feature request related to a problem? Please describe.**

Consider:

```
Steps: [name=string]: #Step | 
    { [#LangCode]: #Step } | 
    { [#ScenarioName]: #Step } | 
    { [#LangCode]: [#ScenarioName]: #Step } | 
    { [#ScenarioName]: [#LangCode]: #Step }

#LangCode = "en" | "fr" // etc

Scenarios: [name=XYZ]: #Scenario

#ScenarioName: or([ for name, _ in Scenarios {name}])
```

The declaration of `Steps` as written is only possible if we can constrain a `#Scenario` name in some way (shown with `XYZ` here) to be any `string` that is not a valid `#LangCode`.

**Describe the solution you'd like**

Potentially something like:

```
not(or(#LangCode))
```

**Describe alternatives you've considered**

A negative specification using `_|_` does work:

```
Scenarios: [#LangCode]: _|_
```

However, it leads to more misleading error messages. 

**Additional context**

**Comment by myitcv** [comment]
Noting an offline conversation: that `not()` is effectively syntactic sugar around [`constrain()`](https://github.com/cuelang/cue/issues/575):

```
x: not(y)

// is equivalent to

x: constrain(x & y == _|_)
```

Which might mean that `not()` is not required (assuming "nice" error messages can be inferred from such negative constraints).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/571.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
