### ISSUE TITLE
cmd/cue: unifying many values is slow

### ISSUE THREAD

**Issue by rogpeppe** [cuelang/cue#572]
commit 1a2105ebef3420a3d9b3e3c384c6e91c1170160c

The following code takes about a minute for me to run. It shouldn't be that slow!

```
import "list"
entries: [for i in list.Range(1, 6300, 1) {key: "\(i)", value: "hello\(i)"}]
unified: {
	for entry in entries {
		"\(entry.key)": entry
	}
}
```

**Comment by myitcv** [comment]
As of 3ef90b326d489a6bf02c0a9527641fd44ae1c319 still takes ~5s.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/572.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
