### ISSUE TITLE
pkg/structs: support ToDefaults()

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#576]
**Is your feature request related to a problem? Please describe.**

Consider:

```
#Person: {
    Name: string
    Address: string
    Age: int
}

x: #Person & {
    Name: "Gopher"
    Address: "Gopher Land"
    Age: 42
}
```

Now consider how we would declare `y` such that it should be a `#Person` with default values taken from those of `x`:

```
y: #Person & {
    Name: *x.Name | _
    Address: *x.Address | _
    Age: *x.Age | _
}
```

i.e. we end up repeating the structure of `#Person`. 

**Describe the solution you'd like**

Something like `structs.ToDefault(v cue.Value)` which takes a struct value (closed or otherwise) and returns a struct value `res` where for each field `x` on `v`, `res: x: *v.x | _`. 

Questions to answer:

* do we consider optional fields?
* does this apply recursively? If so, what about lists?

**Describe alternatives you've considered**

As above, writing everything out "by hand"

**Additional context**

n/a

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/576.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
