### ISSUE TITLE
encoding/openapi: array item type is sometimes expanded when a reference could have been used

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#58]
The reason for this is that cue evaluates list types too aggressively. This does not change the result of a usual CUE evaluation, but it does disallow introspection of intermediate results as is needed by the openapi package.

There are several ways to handle this, but most ideally and most consistently, cue could treat list item types analoguously to struct templates.

Alternatives are to track more origin information in result nodes.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/58.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
