### ISSUE TITLE
Generated Go *.pb.go refers to a non-go-getable package.

### ISSUE THREAD

**Issue by dwilson1988** [cuelang/cue#581]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version devel linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Created a proto file for my dataset. This can be reproduces with the following proto:

"dataset.proto"
```protobuf
syntax = "proto3";
package protos;

import "cue/cue.proto";
option go_package = "my.org/protos";

message Test {
  string test = 1;
}
```

I ran protoc on this with the following commands:
```bash
include = ${GOPATH}/src/cuelang.org/go/encoding/protobuf

protoc \
  -I=./protos \
  -I=${include} \
  --go_out=./protos \
  --go_opt=paths=source_relative \
  dataset.proto
```
Note: I tried withouth source_relative as well.

This created the following (abridged) dataset.pb.go:
```golang
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: dataset.proto

package protos

import (
	_ "cuelang.org/cueproto"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test string `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
}
```

### What did you expect to see?
The problem is the import  "cuelang.org/cueproto" refers to a package that's not go-getable.
```
$ go get cuelang.org/cueproto
go get cuelang.org/cueproto: unrecognized import path "cuelang.org/cueproto": reading https://cuelang.org/cueproto?go-get=1: 404 Not Found
```

### What did you see instead?
I would expect the generated pb to refer to a path that I could access, but that module doesn't appear to be accessible. 

I'm guessing that refers to a package under "cuelang.org/go/encoding/protobuf", as that's where the proto file was, but that refers to it's go_package as "cuelang.org/cueproto".  

Perhaps I am missing something, but I am stumped.

**Comment by verdverm** [comment]
Where are you doing your protobuf work from?

Are you accidentally picking up this file? https://github.com/cuelang/cue/blob/master/encoding/protobuf/cue/cue.proto

**Comment by dwilson1988** [comment]
@verdverm, sorry, somehow I didn't notice this...

I didn't make this clear in my original description, but I'm applying cue constraints in my actually application and using that to generate a schema. E.g.:

```protobuf
message Dataset {
  // machine parsable dataset name
  string name = 1 [(cue.val) = '=~"^[a-z0-9]+(?:-[a-z0-9]+)*$"'];
}
```

So I guess I'm not accidentally picking up that file, that's an explicit import since I need it for my constraints/schema gen.

**Comment by mpvl** [comment]
This is probably related to #450.

The respective proto is in `encoding/protobuf/cue/cue.proto`, so you'll have to include that in your path when evaluating.

Suggestions on how to make this clearer or what would be a better approach is welcome.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/581.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
