### ISSUE TITLE
interpolation with a bool fails

### ISSUE THREAD

**Issue by jba** [cuelang/cue#582]
The spec says string interpolation should work with a bool, but this:
```
a: true
b: "\(a)"
```
fails with `b: expression in interpolation must evaluate to a number kind or string (found bool)`.

**Comment by myitcv** [comment]
This is working at `tip` FWIW. It was fixed as part of https://cue-review.googlesource.com/c/cue/+/6951

**Comment by jba** [comment]
The latest tagged version is from July. Perhaps it's time for a new tag.

**Comment by myitcv** [comment]
`v0.3.0` will (I think) be tagged when issues with the new evaluator have been ironed out.

`v0.3.0-alpha4` is the most recent alpha: https://github.com/cuelang/cue/releases/tag/v0.3.0-alpha4

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/582.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
