### ISSUE TITLE
cmd/cue: strings.Join fails with [string, ...string] list

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#585]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +aa87887 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
-- x.cue --
package x

import "strings"

#c: {
	list: [...string]
	result: strings.Join(list, " ")
}

c: #c & {
	list: ["a", "b", "c"]
}
```

```
$ cue eval
```

### What did you expect to see?

```
#c: {
    list: []
    result: ""
}
c: {
    list: ["a", "b", "c"]
    result: "a b c"
}
```

### What did you see instead?

```
#c.list.0: error in call to strings.Join: element 0 of list argument 0: non-concrete value string
```

**Comment by mpvl** [comment]
I can't seem to reproduce this on tip or even the indicated version. Could you please verify?

**Comment by myitcv** [comment]
That is very strange. I can't repro this either. Closing for now. Will re-open if I can find out what version triggered this.

**Comment by leoluk** [comment]
I stumbled upon this while porting an internal repo to the new evaluator. It reproduces with `[string, ...string]`:

```
-- x.cue --
package x

import "strings"

#c: {
	list: [string, ...string]
	result: strings.Join(list, " ")
}

c: #c & {
	list: ["a", "b", "c"]
}
```

Is this a bug or a feature?

**Comment by myitcv** [comment]
Thanks @leoluk. Re-opening because this does indeed appear to be an issue as of 778719ed:

```
exec cue eval 

-- x.cue --
package x

import "strings"

#c: {
	list: [string, ...string]
	result: strings.Join(list, " ")
}

c: #c & {
	list: ["a", "b", "c"]
}
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/585.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
