### ISSUE TITLE
cue: hang for circular comprehensions

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#587]
### What version of CUE are you using (`cue version`)?

cfd0116c5fb065dd4d055236055b067177b70e1b

### What did you do?

```
root: {
	a: [...int]

	for x in a {
		"\(x)": {}
	}

	b: [ for x in root {x}]
}

```

or in short

```
root: a: [ for x in root {x}]
```

### What did you expect to see?

A structural cycle.

### What did you see instead?

Hang.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/587.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
