### ISSUE TITLE
cue: spurious structural cycle

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#588]
### What version of CUE are you using (`cue version`)?

<pre>
cfd0116c5fb065dd4d055236055b067177b70e1b
</pre>

### What did you do?

```
a: {
	x: c.x
}
b: {
	x: a
	y: "foo"
}
c: {
	x: b.y
}
```

### What did you expect to see?

```
a: {
    x: "foo"
}
c: {
    x: "foo"
}
b: {
    x: {
        x: "foo"
    }
    y: "foo"
}
```

### What did you see instead?

```
b.x: structural cycle:
    ./foo.cue:9:5
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/588.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
