### ISSUE TITLE
Closedness not properly propagated through comprehensions

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#595]
### What version of CUE are you using (`cue version`)?

tip at 317792a5c

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
#cfgs: [{
	name: "foo"
}]
for cfg in #cfgs {
	files: cfg.nam
}
```

### What did you expect to see?

Failure with an full error. Internal debug output:
```
          #cfgs: (#list){
            0: (struct){
              name: (string){ "foo" }
            }
          }
          files: (_|_){
            // [eval] files: undefined field nam:
            //     /tmp/test/x.cue:30:13
          }
```

### What did you see instead?

Note the "incomplete" error type in the below. This is not correct, as "nam" can never be a valid field as the struct is closed.
```
          #cfgs: (#list){
            0: (struct){
              name: (string){ "foo" }
            }
          }
          files: (_|_){
            // [incomplete] files: undefined field nam:
            //     /tmp/test/x.cue:30:13
          }
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/595.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
