### ISSUE TITLE
pkg/encoding: missing support for base64

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#61]
Atm. cue has no builtin's for encoding and decoding strings with base64.
base64 encoded values are used by kubernetes secrets.

I guess a good starting point is the `encoding/hex` package. I also would like to implement the missing functionality.

**Comment by xinau** [comment]
Since I'm new to Gerrit and not sure if I've done everything correct.
I'm going to link this here https://cue-review.googlesource.com/c/cue/+/2600

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/61.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
