### ISSUE TITLE
Invalid template argument does not show error

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#610]
### What version of CUE are you using (`cue version`)?

tip 6de877a

### What did you do?

```
package a

#env: {
        foo: string
}

c1: string & ("dev" | "prod")
c2: string

envs: [c1]: #env
envs: {
        dev: {
                foo: "bar"
        }

        bad1: {
                foo: "bar"
        }

        bad2: {
                foo: 1
        }
}
```

### What did you expect to see?

An error, ideally about passing a disjunction (or not a string) to the template argument, since templates only allow strings there currently

### What did you see instead?

```
#env: {
    foo: string
}
c1: "dev" | "prod"
c2: string
envs: {
    dev: {
        foo: "bar"
    }
    bad1: {
        foo: "bar"
    }
    bad2: {
        foo: 1
    }
}
```

**Comment by verdverm** [comment]
This one causes a panic:

```
package parse

foo: [string]: string

bar: [for x in [1,2,3] {x}]: string
```

**Comment by verdverm** [comment]
```
package parse


foo: [string]: string

bar: [for x in [1,2,3] {x}]: string
```

Looks like the parse accepts a `listLit` in this spot and that is the source of this behavior

**Comment by mpvl** [comment]
The first case (passing a disjunction) to a pattern constraint is valid. Pattern constraints `[pattern]: T` match fields where the field name unifies with the pattern. So a disjunction is valid there. It is also valid to not match anything. Note that pattern constraints are "optional" fields.

What you probably want here is that, additionally, no other fields are allowed. That is possible if the pattern constraint is part of a closed struct. Something like:

```
package a

#env: {
        foo: string
}

c1: string & ("dev" | "prod")
c2: string

#envs: {[c1]: #env}
envs: #envs
envs: {
        dev: {
                foo: "bar"
        }

        bad1: {
                foo: "bar"
        }

        bad2: {
                foo: 1
        }
}
```

**Comment by mpvl** [comment]
The crash should be fixed of course.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/610.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
