### ISSUE TITLE
cue eval -H stopped showing hidden fields

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#615]
broken at this commit: https://github.com/cuelang/cue/commit/b4aa96d77478248fdfe6520c0a57a01628180bf6

```
cue eval -H hidden.cue
-- hidden.cue --
A: {
        _noshow: "hello"
        isshown: "world"
}
```

**Comment by verdverm** [comment]
adding a package clause does work, so is this a semantic change or should this example work?

**Comment by mpvl** [comment]
It's a good question. I don't remember if I did this deliberately, but it makes sense: files from anonymous packages (or files without a package clause) can be combined into a single package at will. Yet, it makes sense to treat the hidden fields of such packages as coming from different namespaces. As we can't display such namespaces, it makes sense to drop them altogether.

If that is really bothersome, we could consider showing hidden fields unconditionally, caveat emptor, as a sort of debugging feature.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/615.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
