### ISSUE TITLE
Concatenate lists with if statement

### ISSUE THREAD

**Issue by PierreAdrienDelisle** [cuelang/cue#623]
Hello, sorry if the question seems stupid but I had a problem understanding how to solve a problem I had. I want to concatenate two lists and the values of those lists depends on a if statement like this :
```
if lb != null {
  let lbDep = ["value"]
}
if ub != null {
  let ubDep = ["secVal"]
}
dep: lbDep+ ubDep

```

The problem here is that they (lbDep/ubDep) arent't in the scope of the var "dep".
But if I initialize them with [] (empty array), I get a "conflicting values" error. 
```
lbDep: []
if lb != null {
  lbDep = ["value"]
}
ubDep:[]
if ub != null {
  ubDep = ["secVal"]
}
dep: lbDep+ ubDep

```

How is it possible to overcome this or re-define an existing value? 
Thanks!

**Comment by verdverm** [comment]
- try initializing with `lbDep: [...]`. `[]` is an empty list while `[...]` is a list of unknown elements
- a `list.FlattenN` in the stdlib too
