### ISSUE TITLE
pkg/struct: use of builtin struct.MinFields gives poor error

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#627]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +778719ed linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cue eval -c

-- cue.mod/module.cue --
module: "mod.com"
-- x.cue --
package x

import "struct"

#y: {...} & struct.MinFields(1)
x:  #y & {
}
```

### What did you expect to see?

An error message that describes precisely where the error is

### What did you see instead?

```
struct has 0 fields < MinFields(1)
```

**Comment by seh** [comment]
Do you have a suggestion for the error message? Perhaps:
> struct has no fields, but at least one field is required

I could see using numbers there, as in "0" and "1" instead of "zero" and "one," but with some care in pluralizing the word "field" correctly.

**Comment by myitcv** [comment]
The error message itself is fine, but it gives no position information. The address (filename:line:col) in the source file should be presented to the user, like all other errors.

**Comment by seh** [comment]
Oh, I misunderstood what you meant when you wrote "precisely where the error is." You meant more physically located, whereas I thought you were using "where" to mean "what is wrong." Here, a more literal interpretation wins.

**Comment by myitcv** [comment]
I should arguably have been more precise 😄

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/627.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
