### ISSUE TITLE
doc: communication channels are missing ?

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#63]
Since I didn't find any documentation about communication channels like mailing list (google groups), instant messengers (irc, slack). The only options I'm left with are 
* opening issues on github and using comments, but this might be the intended format.
* writing personal emails, but information is not available to new comers. 

Imho. easy way to resolve this issue would be creating a google group and adding the missing documentation.

**Comment by mpvl** [comment]
I've added this slack account:
https://join.slack.com/t/cuelang/shared_invite/enQtNjk1NzU1MzMwMjI2LWQ0ZDA2OTRjYTQ0MGUyZDBiYWIzZjVhZGI1YWVlNTVmMWU3MTFhY2MxZmRmMjBiMTA5MGQ1YzUyMmMzN2IxYzc

Let me know if there is something I can change.

**Comment by xinau** [comment]
Opened Change: https://cue-review.googlesource.com/c/cue/+/2660

**Comment by mpvl** [comment]
@betawaffle Thanks for letting us know. It is updated at cuelang.org. Readme in the works.

**Comment by xinau** [comment]
Updated readme with the following change https://cue-review.googlesource.com/c/cue/+/3020

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/63.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
