### ISSUE TITLE
Add codecoverage integration/badge to README.md

### ISSUE THREAD

**Issue by andriisoldatenko** [cuelang/cue#638]
tl;dr it would be great to have codecoverage report generated by codecov, coveralls, gocover

wdyt?

**Comment by verdverm** [comment]
My $0.02 is that a Go specific one would likely be best.

I have tried most general commercial services and find they are quite bad. Codecov provides quite misleading results / badges and should be avoided. Sonarcloud is my fav and has a bunch of extra stuff.

Gocover.io looks nice. I haven't "shopped" around for Go specific.

**Comment by mpvl** [comment]
One issue with code coverage for CUE is that the code is not always tested in the same package as in which it is written. As a result, the basic configuration for code coverage can be misleading: in practice it is considerably higher.

With the recent merger of packages `adt` and `eval` this is somewhat mitigated, but still.

Go _does_ allow cross-package code coverage. It just needs to be set up properly and I haven't taken the time to do that. But if someone wants to do it end-to-end, I'll be happy to include it.

**Comment by verdverm** [comment]
Is that where you have to merge test coverage reports or something? Do you have links to where this is doc'd or talked about?

**Comment by mpvl** [comment]
I forgot what the command was or where it is documented, but there should be an option in to `go` tool for allowing setting up that kind of merging.

**Comment by verdverm** [comment]
It's somewhere in the Go source. I pulled this from it https://github.com/hofstadter-io/hof/blob/_dev/script/runtime/go-cover.go

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/638.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
