### ISSUE TITLE
cue fmt ./... returns `non-matching package names (* != _)`

### ISSUE THREAD

**Issue by eonpatapon** [cuelang/cue#644]
### What version of CUE are you using (`cue version`)?

beta.2

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
-- cue.mod/module.cue --
module: "example.com/x"
-- x.cue --
package x

foo: string

a: [string]: int
```

```
 cue fmt ./...
non-matching package names (* != _)
 echo $?
1
```

### What did you expect to see?

```
 cue fmt ./...
 echo $?
0
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/644.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
