### ISSUE TITLE
cmd/cue: get go generates invalid code

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#648]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +f0c025c1 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cat <<'EOD' | testscript -v
exec go mod init blah
exec cue mod init blah.com
exec go get mvdan.cc/sh/v3@v3.2.1
exec cue get go mvdan.cc/sh/v3/...
exec cue def mvdan.cc/sh/v3/syntax
EOD
```

### What did you expect to see?

Success.

### What did you see instead?

```
> exec go mod init blah
[stderr]
go: creating new go.mod: module blah
> exec cue mod init blah.com
> exec go get mvdan.cc/sh/v3
[stderr]
go: mvdan.cc/sh/v3 upgrade => v3.2.1
> exec cue get go mvdan.cc/sh/v3/...
> exec cue def mvdan.cc/sh/v3/syntax
[stderr]
package "io" not found:
    ./cue.mod/gen/mvdan.cc/sh/v3/syntax/parser_go_gen.cue:7:8
[exit status 1]
```

Per offline discussion with @mpvl, Go standard library packages need to mapped to a domain-qualified module path. Perhaps something like `golang.org/pkg/io` etc.

**Comment by myitcv** [comment]
Another good test case here is https://github.com/goreleaser/goreleaser/discussions/2065

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/648.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
