### ISSUE TITLE
cmd/cue: fmt should not attempt to resolve imports

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#653]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +c58e0ffc linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
testscript <<'EOD'
exec cue fmt x.cue

-- x.cue --
package x

import "blah.com/rubbish"

x: 5
EOD
```

### What did you expect to see?

No error

### What did you see instead?

```
[stderr]
import failed: cannot find package "blah.com/rubbish":
    ./x.cue:3:8
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/653.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
