### ISSUE TITLE
Another cycle issue

### ISSUE THREAD

**Issue by Ereski** [cuelang/cue#655]
Similar to my previous [issue](https://github.com/cuelang/cue/issues/622) but this one is even simpler:

```
import "regexp"

X: Y.host
Y: {
    #components: regexp.FindNamedSubmatch(#"^(?P<host>[[:alnum:].]+)$"#, X)
    host: #components.host
}

X: "example.com"
```

This example causes a cycle error even it should be solvable.

**Comment by Ereski** [comment]
Again, replacing `X` in the regex call with a concrete value works as expected

**Comment by Ereski** [comment]
Also, I can't compile this through the API (cycle error) instead of erroring out on a lookup

**Comment by mpvl** [comment]
The API does a full evaluation for the root value. The reason for this is that logically a value is invalid if any of its descendants is invalid.

But you are right that this is a valid value in the first place and that there should not be an error.

**Comment by Ereski** [comment]
Even simpler:

```cue
X: Y.host
Y: regexp.FindNamedSubmatch(#"^(?P<host>[[:alnum:].]+)$"#, X)

X: "example.com"
```

**Comment by Ereski** [comment]
@mpvl I can `Compile` this no problem:

```cue
X: Y + 1
Y: X - 1
```

The I use `Fill` to unify either `X` or `Y` with a concrete value. In this example `Compile` fails before I get to call `Fill`.

**Comment by mpvl** [comment]
Thanks for all the details and finding all these cases!

It seems to be related to it passing to a builtin. Either way, this should be fixed.

It could make sense as Fill doesn't necessarily change anything: it just adds a conjunct at the end, but it won't work around the bug per se.

**Comment by mpvl** [comment]
One way to work around it for now is to move the first `X` field down. But that is not very satisfying, of course. Order shouldn't matter for one.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/655.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
