### ISSUE TITLE
general: goreleaser is failing

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#671]
e.g. https://github.com/cuelang/cue/actions/runs/505973324

Creating this issue as a reminder to investigate. 

Any ideas @zchee?

**Comment by zchee** [comment]
will check it

**Comment by myitcv** [comment]
Thanks - only if you have time, otherwise I will get around to looking into it.

**Comment by zchee** [comment]
@myitcv will investigate today(now 10:15AM in JST)

**Comment by zchee** [comment]
@myitcv also, feel free to assign to me

**Comment by mpvl** [comment]
FYI:
```
$ goreleaser --version

version: 0.110.0
commit: 3f082c9252eb93a4bdf5045e06accbde37bb6dc3
built at: 2019-06-13T01:36:45Z
built by: goreleaser
```
The  problem is that the existing configuration requests the latest Docker image of goreleaser. 

@zchee: do you know where to specify a specific version for goreleaser?

**Comment by zchee** [comment]
@mpvl I'm not feeling well, will investigate tomorrow. sorry🙏

**Comment by verdverm** [comment]
@mpvl The `goreleaser` version can be added to the GH action under the `with`. They have an example here: https://goreleaser.com/ci/actions/#workflow

**Comment by myitcv** [comment]
Looking to fix this in https://cue-review.googlesource.com/c/cue/+/8404

**Comment by myitcv** [comment]
@zchee - hope you feel better.

Hopefully my fix is the right one?! We can obviously fix in a later CL if not.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/671.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
