### ISSUE TITLE
It is not clear which types can be converted to CUE

### ISSUE THREAD

**Issue by Ereski** [cuelang/cue#676]
In functions that accept `interface{}` and are converted to CUE values, for example [Instance.Fill](https://pkg.go.dev/cuelang.org/go/cue#Instance.Fill), it is not clear which types are accepted. Furthermore it looks like putting the wrong types will cause an unrelated panic deep down some internal source file, with no indication that it was caused by a bad argument.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/676.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
