### ISSUE TITLE
Docs: Tour has two similar "Definitions" lessons

### ISSUE THREAD

**Issue by extemporalgenome** [cuelang/cue#678]
https://cuelang.org/docs/tutorials/tour/intro/schema/ and https://cuelang.org/docs/tutorials/tour/types/defs/ have the same title and similar first sentences (with some identical wording introducing syntax).

When reading through the tutorial quickly, I mistakenly believed that the tutorial "next" links entered into a loop.

Perhaps these two lessons can be combined, or at least given different titles to make them more distinct.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/678.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
