### ISSUE TITLE
encoding: missing support for toml

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#68]
(Go) Tools like InfluxDB, GitLab CI (Runner), Traefik use [TOML](https://github.com/toml-lang/toml) as their configuration language. Atm. CUE has no encoding support for TOML configuration files to be imported or exported. Since Go doesn't have native support for TOML, a [third-party implementation](https://github.com/toml-lang/toml/wiki#implementations) needs to be imported as it's the case for YAML. Another thing to be aware of is that the native support for Date-Time, Date, Time values in TOML. Maybe this could be something CUE might want to support in the future as well. Also a mapping of [array of tables](https://github.com/toml-lang/toml#array-of-tables) to a appropriate CUE representation might be needed.

**Comment by mpvl** [comment]
I'm fine with TOML, being as common as it is, to be one of the few more configuration formats that's natively supported. At the moment, YAML, JSON, Go, Proto, and OpenAPI are higher on the list to complete support for, though.

Note that generating TOML output should already not be too hard using the text/template builtin package.

CUE has some limited support for time and date parsing through the time builtin package. It is high on the list to complete this support as part of the OpenAPI support effort. With this, a time field is indicated as:
```
import "time"

meetingTime: time.Time
```
where meetingTime is a string with the respective time format.

I don't understand why arrays of tables are not just lists of values. It seems to be a special TOML notation that needs no special treatment in CUE. I do plan to add support for associative lists at some point, which would allow one to define different items of a list at different locations, though, sticking to CUE's associativity and commutativity properties, without any guarantee of order other than adhering to some topological sort.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/68.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
