### ISSUE TITLE
Wrong result for `meet`

### ISSUE THREAD

**Issue by Ereski** [cuelang/cue#680]
Latest CUE (726d93e).

The following should be an error:

```cue
$ cue export - <<EOF
(>10 * 2) & 0
EOF
```

Instead CUE outputs `0`.

**Comment by mpvl** [comment]
Hah, this was a TODO I missed. Fix coming up.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/680.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
