### ISSUE TITLE
cue/load: provide API for checking untrusted CUE prior to loading

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#689]
**Is your feature request related to a problem? Please describe.**

Per `cue help filetypes`, `cmd/cue` provides a number of different input types to constrain the base `cue` input type:

```
    Tag         Description
    data        Require concrete input and output that does
                not require any evaluation.
    graph       Like data, but allow references.
    schema      Export data and definitions.
```

This is particularly useful when loading untrusted CUE. The existence of comprehensions mean that an attacker could DoS a service/program.

However, there does not appear to be a means limiting the type of CUE loaded via the API (`load.Instances`), or indeed for CUE compiled from arbitrary source (`cue.Runtime.Compile`). 

Another option might be to provide a validation/check method given an AST.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/689.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
