### ISSUE TITLE
Another order-dependency issue when evaluating a cycle

### ISSUE THREAD

**Issue by Ereski** [cuelang/cue#695]
HEAD: 10a48e9

```
import "regexp"

X: "message: hello"

X: #aux.message

#aux: {
    if Y.message == _|_ {
        message: ""
    }
    if Y.message != _|_ {
        message: "message: " + Y.message
    }
}

Y: regexp.FindNamedSubmatch(#"^(message: (?P<message>.*))?$"#, X)
```

Puttihg `X: "message: hello"` anywhere but the top leads to `X` being recalculated with the wrong value (the empty string), causing a conflict

**Comment by mpvl** [comment]
Thanks for cranking these out! Will take a look.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/695.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
