### ISSUE TITLE
Incorrect tutorial example (or confusing?)

### ISSUE THREAD

**Issue by yannk** [cuelang/cue#696]
I was reading through the tutorial and in the "Validation" section at:

   https://cuelang.org/docs/tutorials/tour/intro/validation/

There are two errors on the page, and the first one about the boolean value didn't make sense to me. So I ran the test and got the output I expected:

```
languages.1.name: invalid value "dutch" (out of bound =~"^\\p{Lu}"):
    ../../../../../../tmp/sch.cue:3:8
```

Should the following removed from the page?
```
languages.2.tag: conflicting values string and false (mismatched types string and bool):
    ./data.yaml:6:11
    ./schema.cue:2:8
```

**Comment by myitcv** [comment]
Dup of #681.

For details on why `no` is a problem see https://yaml.org/type/bool.html

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/696.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
