### ISSUE TITLE
cmd/cue: add "hoist" command

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#7]
Implement `cue hoist` to extract templates from concrete data definitions. One could see this as `cue trim` in the opposite direction.

This can be implemented using the known anti-unification algorithm. It probably makes sense, though, to disregard disjunctions or to limit the number of elements.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/7.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
