### ISSUE TITLE
cmd/cue: improve error messages for get go

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#701]
As a follow up to #621 (and in preparation for #646) we should ensure we have good error messages for `cue get go`:

* in case a dependency is not available/cannot be resolved (i.e. properly surfacing `go/packages` errors)
* in case a target package cannot be properly type checked. Including:
  * syntax errors
  * type checking errors

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/701.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
