### ISSUE TITLE
cmd/cue: cmd sub command task does not execute with working directory of instance

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#708]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +bedb047a linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
testscript <<'EOD'
exec cue cmd createFile ./a/b
exists a/b/hello.txt

-- a/b/x_tool.cue --
package x

import (
	"tool/file"
)

command: createFile: file.Create & {
	filename: "hello.txt"
	contents: "hello world!"
}
EOD
```

### What did you expect to see?

Passing test

### What did you see instead?

```
> exec cue cmd createFile ./a/b
> exists a/b/hello.txt
FAIL: /tmp/testscript318574194/-/script.txt:2: $WORK/a/b/hello.txt does not exist
```

`cue help cmd` is not specific on this, but much like `go test` or `go generate` I would expect the working directory of a task to be that of the instance for which the task is currently executing.

**Comment by myitcv** [comment]
Discussed with @mpvl and we concluded the semantics described above do not make sense.

Instead, when `cue cmd` is rewritten as `cuerun` we will solve the underlying problem because you will instead write something like:

```
cuerun ./path/to/tool/pkg commandname arguments...
```

i.e. the distinction between the package that declares the tool, and arguments to the command being run is made clear.

Whilst this fundamentally doesn't alter the fact the working directory will not change, it better frames why it's correct not to do that.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/708.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
