### ISSUE TITLE
doc: automated testing of all docs

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#712]
This is an umbrella issue for ensuring that all of our docs are covered by automated tests in some way, including things like the [project README](https://github.com/cuelang/cue/blob/master/README.md). 

For this we could well leverage [`preguide`](https://github.com/play-with-go/preguide).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/712.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
