### ISSUE TITLE
cue trim bug: "imported and not used" errors

### ISSUE THREAD

**Issue by vikstrous2** [cuelang/cue#716]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version v0.3.0-beta.3.0.20210203172046-09cd07bb63ed linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes, this is the latest master

### What did you do?

Directory structure:
```
cue.mod
...
├── module.cue
...
kubernetes/
├── k8s_defs.cue
└── stuff.cue
```

module.cue
```
module: ""
```

Populate `cue.mod/gen` with:
```
cue get go k8s.io/api/apps/v1
```

k8s_defs.cue
```
package kube

import (
        apps_v1 "k8s.io/api/apps/v1"
)

deployment: [string]: apps_v1.#Deployment
```
stuff.cue
```
package kube

if true {
        deployment: "name": {}
}

deployment: [ID=_]: spec: template: spec: {
        containers: []
}
```
command:
```
cd kubernetes
cue trim ./...
```

### What did you expect to see?

success

### What did you see instead?
```
imported and not used: "k8s.io/api/apps/v1" as apps_v1:
    ./k8s_defs.cue:4:2
```

### Bonus mystery:
If you change stuff.cue to import "strings", that seems to "fix" this bug:

stuff.cue
```
package kube

import "strings"

if true {
        deployment: "name": {}
}

deployment: [ID=_]: spec: template: spec: {
        containers: [{name: strings.Join(["a"], "a")}]
}
```

**Comment by vikstrous2** [comment]
This bug is not present in cue v0.2.2. Looks like downgrading makes trim work again.

**Comment by mpvl** [comment]
Trim has very recently been completely rewritten, so it is certainly possible this introduced a regression.

**Comment by myitcv** [comment]
Reduced this down to:

```
exec cue eval ./...
exec cue trim ./a
exec cue trim ./b

-- a/a.cue --
package a

#Deployment2: {
	spec: []
}
-- b/b.cue --
package b

import (
	"example.com/blah/a"
)

deployment: [string]: a.#Deployment2

if true {
	deployment: "name": {}
}

deployment: [string]: spec: []
-- cue.mod/module.cue --
module: "example.com/blah"
```

Gives:

```
> exec cue eval ./...
[stdout]
#Deployment2: {
    spec: []
}
// ---
deployment: {
    name: {
        spec: []
    }
}
> exec cue trim ./a
> exec cue trim ./b
[stderr]
imported and not used: "example.com/blah/a":
    ./b/b.cue:4:2
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/716.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
