### ISSUE TITLE
Cue fmt drags comments into import block

### ISSUE THREAD

**Issue by ah-edg** [cuelang/cue#720]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.3 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

Run `cue fmt` on this input:
```
import "encoding/base64"

// comment

#A: {}

```

### What did you expect to see?

no change

### What did you see instead?

```
import ( "encoding/base64"

	// comment
)

#A: {}
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/720.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
