### ISSUE TITLE
cue fmt indents top-level comments

### ISSUE THREAD

**Issue by bbkane** [cuelang/cue#722]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.3 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
$ cat fields.cue
// comment
hello: "world"
$ cue fmt
```

### What did you expect to see?

```
$ cat fields.cue
// comment
hello: "world"
```

### What did you see instead?

```
$ cat fields.cue
	// comment
hello: "world"
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/722.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
