### ISSUE TITLE
cmd/cue: fmt should not attempt to resolve imports

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#728]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +fdccfbc5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

A variation on #653 

```
exec cue fmt x.cue
rm a/a.cue
exec cue fmt x.cue

-- a/a.cue --
package a
-- cue.mod/module.cue --
module: "mod.com"
-- x.cue --
package x

import "mod.com/a"

x: 5
```

### What did you expect to see?

No error

### What did you see instead?

```
> exec cue fmt x.cue
> rm a/a.cue
> exec cue fmt x.cue
[stderr]
import failed: build constraints exclude all CUE files in mod.com/a (ignored: x.cue):
    ./x.cue:3:8
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/728.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
