### ISSUE TITLE
cmd/cue: better error message required when provided .cue files are not valid

### ISSUE THREAD

**Issue by egidijusz** [cuelang/cue#741]
Hello,

as title says - cue fails to parse files passed as cli arguments if filenames contain underscore (_).

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.2.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
<pre>
$ echo 'foo: "bar"' > sometest.cue
$ cue eval sometest.cue
foo: "bar"
$ mv sometest.cue some_test.cue
$ ls some_test.cue
some_test.cue
$ cue eval some_test.cue
no CUE files in command-line-arguments
</pre>

### What did you expect to see?
`foo: "bar"`

### What did you see instead?
`no CUE files in command-line-arguments`

**Comment by mpvl** [comment]
`_test.cue` is reserved for CUE test files.

**Comment by egidijusz** [comment]
This is correct.
`cue eval|export` works fine with `foo_bar.cue` for example.

I had a case of tunnel-vision when trying to import configs of test servers (conveniently suffixed with _test.yml). :facepalm: 

Sorry for false alarm and thank you for your time!

P.s. I'm not sure if I should close the issue now (because of new label, `roadmap/errors`).

**Comment by myitcv** [comment]
Thanks @egidijusz - we'll leave this open - I've retitled the issue to better reflect what we need to do.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/741.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
