### ISSUE TITLE
community: Slack invite via Google OAuth expired

### ISSUE THREAD

**Issue by abursavich** [cuelang/cue#744]
New users cannot join the Slack workspace.

> # Invitation expired
> 
> It looks like you’re trying to accept an invitation, but the link was deactivated.
> 
> Contact the person who originally invited you about getting a new link or manually inviting you.

https://github.com/cuelang/cuelang.org/blob/18fa0fb770422adfcc4bc83ada1a30766620f236/config.toml#L159

**Comment by myitcv** [comment]
For better visibility I've moved this issue to the main CUE repo.

**Comment by myitcv** [comment]
Apparently this is now fixed (tested myself). @abursavich please can you check from your side?

**Comment by abursavich** [comment]
LGTM

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/744.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
