### ISSUE TITLE
doc: Modules, Packages, and Instances docs should be clarified to not imply special pkg directory

### ISSUE THREAD

**Issue by smorel-plenty** [cuelang/cue#753]
In the section on [import paths](https://cuelang.org/docs/concepts/packages/#import-path) there's a mention of `module: example.com/pkg`. I'm assuming the `pkg` here is not referring to the `pkg` cue-managed external dependencies directory but could instead be something like `module example.com/mypackage` for better clarity when reading the docs?

**Comment by myitcv** [comment]
Moved this issue to the main CUE repo for tracking.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/753.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
