### ISSUE TITLE
cmd/cue: structural cycle reported where there doesn't appear to be one

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#754]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +760aa115 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval

-- x.cue --
package main

Template: {
	from: _

	task: from
}

C: Template & {
	from: Template & {
		from: Template & {}
	}
}
```

### What did you expect to see?

Passing test with output:

```
C: {
    from: {
        from: {}
    }
}
```

### What did you see instead?

```
> exec cue eval
[stderr]
C.task.task: structural cycle
```

**Comment by mpvl** [comment]
Analysis: this is indeed not a structural cycle. This very specific pattern simulates Template referencing itself, which is what cycle detection picks up (note that the cycle is in `C.task.task`, not `C.from.from`).

This is best addressed moving to structure sharing. A side-benefit of structure sharing is making it considerably easier to do cycle detection (as well as implementing concurrency, see graph-unification papers from Tomabechi and Van Lohuizen).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/754.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
