### ISSUE TITLE
cue: (constrained) lists of values disproportionately increase evaluation time 

### ISSUE THREAD

**Issue by myitcv** [cuelang/cue#756]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +760aa115 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

I've linked to a non-minimal repro here because otherwise the timing differences are imperceivable. 

The example is based on the CUE repo's own [GitHub workflow definitions](https://github.com/cuelang/cue/blob/master/internal/ci/workflows.cue).

https://gist.github.com/myitcv/b61bc5dbc67ebafd76fa6c7c93c0f229

The base timing value is a pure `cue eval` of the workflow declarations themselves. These correspond to the fields `test`, `repository_dispatch`, `release`, `rebuild_tip_cuelang_org` and `mirror`.

```
> exec time -p cue eval --out cue -o tmp/out
[stderr]
real 0.18
```

If we now add the following:

```
workflows: [
	{
		file:   "test.yml"
		schema: test
	},
	{
		file:   "repository_dispatch.yml"
		schema: repository_dispatch
	},
	{
		file:   "release.yml"
		schema: release
	},
	{
		file:   "rebuild_tip_cuelang_org.yml"
		schema: rebuild_tip_cuelang_org
	},
	{
		file:   "mirror.yml"
		schema: mirror
	},
]
```

i.e. a simple list that contains those values, execution time jumps by almost 100%:

```
> exec time -p cue eval --out cue -o tmp/out
[stderr]
real 0.31
```

If we further constrain `workflows` as follows:

```
package ci

import (
	"github.com/SchemaStore/schemastore/src/schemas/json"
)

workflows: [...{file: string, schema: (json.#Workflow & {})}]
```

then the execution time jumps massively:

```
> exec time -p cue eval --out cue -o tmp/out
[stderr]
real 0.90
```

These three timings are given by the script in the txtar:

```
exec time -p cue eval --out cue -o tmp/out
cp a.cue.simple_list a.cue
exec time -p cue eval --out cue -o tmp/out
cp a.cue.constrained_list a.cue
exec time -p cue eval --out cue -o tmp/out
```

### What did you expect to see?

Not dissimilar execution times in all three scenarios.

### What did you see instead?

As above.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/756.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
