### ISSUE TITLE
spec: definition of binary_digit missing

### ISSUE THREAD

**Issue by jansorg** [cuelang/cue#765]
At https://cuelang.org/docs/references/spec/#integer-literals `binary_digit` is referenced, but it's not defined at https://cuelang.org/docs/references/spec/#letters-and-digits.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/765.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
