### ISSUE TITLE
Allow attributes for list elements

### ISSUE THREAD

**Issue by verdverm** [cuelang/cue#774]
### What version of CUE are you using (`cue version`)?

`beta.5` 

### Does this issue reproduce with the latest release?

likely

### What did you do?

```
list: [
    { a: "a" } @myattr(),
    { b: "b" }
]
```

### What did you expect to see?

expected output when the attr is not present

### What did you see instead?

An error: `failed to load: missing ',' in list literal (and 1 more errors)`

**Comment by mpvl** [comment]
Yes, this is currently not allowed in the spec. It arguably should.

Would be good to document use cases in this Issue to help with prioritization. So what could you solve with this than you cannot solve with the current functionality.

**Comment by verdverm** [comment]
The list is docker image layers, technically Buildkit.

I'd like to annotate which layers to `@eject(<image-name>)` into the external container registry. Buildkit lets you do this with any layer. Another thing I'd like to do is use an annotation to drop into a debug session at any given layer (another thing Buildkit supports).

These sorts of things don't feel as right as Cue config, but seem to align well with attributes. It's specific to a tool, isn't part of the schema in this case, and stands out more from a DX perspective. I'd also like to have the "eject" annotation at both the layer and the image levels. It's easier in this case to ask for an annotation on an arbitrary Cue value than add a field to unknown numbers of defs and structs.

I know I could easily add Cue fields to solve this, but that feels like it will end in code sprawl. Attributes seem like a win here.

**Comment by mpvl** [comment]
Makes sense. Also, to CUE list elements are almost indistinguishable from struct fields, so this would be consistent.

One thing you could consider, though, is to make them declaration attributes:
```
a: [
    {
          @buildkit(debug=...)
    },
]
```
With embedded scalars this can be considered a general solution.

**Comment by verdverm** [comment]
Is it possible to get at those attributes today? They aren't returning from the `Value.Attribute(<>)` call

**Comment by mpvl** [comment]
I'll close this for now. The new attribute API should provide what is needed here.

If this is still insufficient, or if there is a specific need for this, feel free to reopen.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/774.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
