### ISSUE TITLE
Language specifiction: Unmatched '[' in ListLit

### ISSUE THREAD

**Issue by jansorg** [cuelang/cue#777]
### What did you expect to see?
A valid definition of `ListLit` at  https://cuelang.org/docs/references/spec/#lists.

### What did you see instead?
`ListLit` is currently defined as `ListLit       = "[" [ ElementList [ "," [ Ellipsis ] ] [ "," ] "]" .`

The are 4 opening `[`, but only 3 closing `]`.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/777.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
