### ISSUE TITLE
error in regexp validation - negation is ignored

### ISSUE THREAD

**Issue by ah-edg** [cuelang/cue#778]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?
`cue eval -c test.cue` on `test.cue`
```
#PortName: string & =~"^[-a-z0-9]{1,15}$" & =~"[a-z]" & !="^-|--|-$"

name: #PortName & "-a"
```

### What did you expect to see?
an error because it's invalid: `!="^-|--|-$"`

### What did you see instead?
`name: "-a"`

**Comment by ah-edg** [comment]
My mistake, a typo. Should have been `!~`, I wrote `!=`. Sorry

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/778.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
