### ISSUE TITLE
Configuration Typo

### ISSUE THREAD

**Issue by hueys** [cuelang/cue#79]
In the "Simplicity at Scale" section everything is missing an 'h':

> For small-scale projects, using inhertiance can be too complex, and the simplicity of spelling everyting out is often a superior approach.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/79.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
