### ISSUE TITLE
Spec: use of "#" not consistent for escaping rules

### ISSUE THREAD

**Issue by jansorg** [cuelang/cue#795]
(apologies for nit picking)

1. An escaped character is defined as:
```
escaped_char     = `\` { `#` } ( "a" | "b" | "f" | "n" | "r" | "t" | "v" | "/" | `\` | "'" | `"` ) .
```

Whereas `octal_byte_value` and siblings are defined without the padding character `#`.

But the escape prefix `{#}` is also supported for these rules, i.e. it should be defined as 
```
octal_byte_value = `\` {#} octal_digit octal_digit octal_digit .
```

2. `interpolation` is also supporting the padding character, but is defined as 
  ```
interpolation    = "\(" Expression ")" .
  ```
  It should be defined as 
  ```
interpolation    = "\" {`#`} "(" Expression ")" .
  ```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/795.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
