### ISSUE TITLE
cmd/cue: def not creating output

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#802]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```
cue get go k8s.io/api/apps/v1
cue def k8s.io/api/apps/v1 -o def.json
```

### What did you expect to see?

`def.json` to exist and contain the def.

### What did you see instead?

`def.json` does not exist.

If using `-` (stdout) it works fine.

**Comment by verdverm** [comment]
did you `go get k8s.io/api/apps/v1`?

Cue does not fetch Go packages and expects them to be available locally already

**Comment by uhthomas** [comment]
Yep, I can see it in my `cue.mod` dir. Running without `-o`, or `-o -`, spits out what I would expect. Using `k8s.io/apimachinery/pkg/util/intstr` for the following snippet as the def is way smaller, but the exact same behaviour with `-o` is observed.

```
$ cue def k8s.io/apimachinery/pkg/util/intstr
package intstr

// IntOrString is a type that can hold an int32 or a string.  When used in
// JSON or YAML marshalling and unmarshalling, it produces or consumes the
// inner type.  This allows you to have, for example, a JSON field that can
// accept a name or number.
// TODO: Rename to Int32OrString
//
// +protobuf=true
// +protobuf.options.(gogoproto.goproto_stringer)=false
// +k8s:openapi-gen=true
#IntOrString: _

// Type represents the stored type of IntOrString.
#Type:     int64
#enumType: #Int | #String
#Int:      #Type & 0
#String:   #Type & 1
```

**Comment by verdverm** [comment]
can you try adding the `--out json` flag to set the output format?

**Comment by uhthomas** [comment]
Yep.
```
$ cue def k8s.io/apimachinery/pkg/util/intstr --out json -o def.json
$ cat def.json
cat: def.json: No such file or directory
```

**Comment by verdverm** [comment]
Can confirm, seeing the same thing on some of my configs. Applies to other formats as well, notably yaml in my tests

**Comment by uhthomas** [comment]
@verdverm Is there anything I can do to help fix this? I can't build my cue manifests at the moment because of it.

**Comment by verdverm** [comment]
would this work for you?

`cue def k8s.io/apimachinery/pkg/util/intstr --out json -o - | def.json`

**Comment by uhthomas** [comment]
Unfortunately not. I'm using Bazel to build these files which does not support commands which print to stdout.

**Comment by verdverm** [comment]
I'm not familiar with Bazel, you might try asking in Slack, there are people around who are

**Comment by uhthomas** [comment]
Actually, thank you for the suggestion. I've forked [rules_cue](https://github.com/tnarg/rules_cue) and made [this change](https://github.com/uhthomas/rules_cue/commit/46863d61bf1fc3fab38033642a541d4fb82bf71b) to use output redirection. 😄

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/802.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
