### ISSUE TITLE
cue export -h has malformed JSON in documentation

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#819]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

`cue export -h`

### What did you expect to see?

Valid documentation.

### What did you see instead?
The documentation states:
```
yields the following JSON:

        {
                "a": 1,
                "b", "my string"
        }
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/819.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
