### ISSUE TITLE
Spec: Incomplete definition of ListLit

### ISSUE THREAD

**Issue by jansorg** [cuelang/cue#823]
ListLit is currently defined as:
```
ListLit       = "[" [ ElementList [ "," [ Ellipsis ] ] [ "," ] ] "]" .
ElementList   = Embedding { "," Embedding } .
```

- This doesn't accept `[...]` and `[...end]`, although `cue eval` seems to to accept both
- the rule would accept `[a,,]`, although that's not accepted by `cue eval`

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/823.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
