### ISSUE TITLE
cmd/cue: Weird formatting when importing large files

### ISSUE THREAD

**Issue by uhthomas** [cuelang/cue#826]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```sh
curl -Lfv https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.yaml > t.yaml
cue import --list t.yaml
```

### What did you expect to see?

A nicely formatted CUE file.

### What did you see instead?

![](https://kipp.6f.io/n4JI0s8Cg8rH.png)

**Comment by uhthomas** [comment]
Another example

![](https://kipp.6f.io/g7nBt0f3f_Pd.png)

**Comment by myitcv** [comment]
Confirmed with 7c5d28e6721a260dc2efdf623a015b5aea195d9e

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/826.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
