### ISSUE TITLE
doc/spec: binary_lit production incorrectly omits "_" separator

### ISSUE THREAD

**Issue by zombiezen** [cuelang/cue#828]
The production for `binary_lit` is:

```
binary_lit  = "0b" binary_digit { binary_digit } .
```

However, the example below permits:

```
0b0101_0001
```

I believe the correct production is:

```
binary_lit  = "0b" binary_digit { [ "_" ] binary_digit } .
```

**Comment by myitcv** [comment]
Thanks for raising this, @zombiezen. Sorry, this got "lost" in the cuelang.org repo.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/828.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
