### ISSUE TITLE
docs: add a section for tips and tricks

### ISSUE THREAD

**Issue by xinau** [cuelang/cue#829]
It could be useful for newcomers to have examples of some more complicated patters like:
* [check if a field exists](https://github.com/cuelang/cue/issues/140#issuecomment-538416872)
  ```
  if a["opt"] != _|_ {
    optional : a.opt
  }
  ```
* wrapping complicate for comprehensions
  ```
  flatten: {
    in: [...]
    out: //  comprehension
  }
  v: (flatten&{in: list}).out
  ```
* selecting specific disjunctions / [simulating else clause using default values](https://github.com/cuelang/cue/issues/111#issuecomment-533790147)
  ```
  x :: * {
      val: string
      out: 1
  } | {
      val: int
      out: 2
  }
  y: (x & {val: "foo"}).out
  z: (x & {out: 1}).val
  ```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/829.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
