### ISSUE TITLE
docs: comparison with Dhall

### ISSUE THREAD

**Issue by marco-m** [cuelang/cue#830]
the Cue documentation [makes comparisons](https://cuelang.org/docs/usecases/configuration/#comparisons) for specific features with languages such as Jsonnet and GCL. Given the popularity and expressiveness of [Dhall](https://dhall-lang.org/), I think it would make sense to have an equivalent comparison section. Thanks!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/830.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
