### ISSUE TITLE
suggest adding code samples to the README

### ISSUE THREAD

**Issue by dcsan** [cuelang/cue#89]
i came from hackernews and it took me a lot of digging before i could actually see what the format/language looks like... would really suggest putting at least some simple examples on the first page, the readme. that would be much quicker to grok than trying to decode the front page.

esp with the tutorial, it's like one idea per page. 
one nice condensed example that shows a few ideas together would be great for quickly getting the idea across.

https://github.com/cuelang/cue/blob/master/doc/tutorial/basics/curly.md

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/89.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
