### ISSUE TITLE
cue/encoding: add standardized deprecated attribute

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#90]
Many of the encodings supported by CUE have a notion of deprecated (Protobuf, OpenAPI, Go). Support a standardized deprecated attribute, like `@deprecated(msg)` to facilitate preserving this information in translations.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/90.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
