### ISSUE TITLE
Validation error for concreteness doesn't include position information

### ISSUE THREAD

**Issue by j-maxi** [cuelang/cue#905]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0-alpha.1.0.20210415183916-c5c9125d9970 linux/amd64
</pre>

### What did you do?

<pre>
$ cat test.cue 
parameters: {
        foo: string
}

$ cue eval -c test.cue
</pre>

### What did you expect to see?

Error message with position information where a value is not concrete.

### What did you see instead?

No position information included.

<pre>
parameters.foo: incomplete value string
</pre>

With v0.2.2, I got position information as follows.
<pre>
$ cue version v0.2.2 linux/amd64

$ cue eval -c test.cue
parameters.foo: incomplete value (string):
    ./test.cue:2:7

</pre>

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/905.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
