### ISSUE TITLE
Recursive proto causes cue cycle when generationg openapi schemas

### ISSUE THREAD

**Issue by sam-heilbron** [cuelang/cue#915]
### What version of CUE are you using (`cue version`)?

<pre>
v0.3.2
</pre>

### Does this issue reproduce with the latest release?
There is an 0.4.0 alpha release that I haven't tried this with yet

### What did you do?

When generating openapi v3 schema from a protobuf definition, if the definition is recursive, the schema is never generated because cue enters a cycle.

The following proto definition causes this:

```proto
message RecursiveMessage {
    string state = 1;
    map<string, RecursiveMessage> subresource_messages = 2;
}

```

### What did you expect to see?
I would expect that this proto can be converted into an openapi schema

### What did you see instead?
This function (https://github.com/cuelang/cue/blob/master/encoding/openapi/openapi.go#L219) enters an infinite loop.

**Comment by mpvl** [comment]
Can you describe the steps to reproduce this? Did you use the API, the command line? Which options?

**Comment by mpvl** [comment]
As far as I can see, this only happens with the `ExpandReferences` option of OpenAPI, which then causes a hang.

This of course still should not hang, but a solution would probably involve returning an error saying that ExpandReferences cannot be used with recursive structures.

So the workaround for now is to not use `ExpandReferences`.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/915.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
