### ISSUE TITLE
cue cmd does not accept flags, interprets them as package

### ISSUE THREAD

**Issue by ah-edg** [cuelang/cue#925]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.2 linux/amd64
# but also
cue version 0.4.0-alpha.2 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

Ran `setup_tool.cue` with contents below like this:
`cue cmd greet --all-errors --ignore --verbose`

file contents:
```
package example

import (
	"tool/cli"
)

command: greet: {
    task: {
        askname: cli.Ask & {
            prompt: "Enter your name"
        }
        hello: cli.Print & {
            "$after": askname
            text: "Hello \(task.askname.response)"
        }
    }
}
```

### What did you expect to see?
A prompt for my name and a Hello X output

### What did you see instead?
`cannot find package "--all-errors"`
allthough it should work:
```
$ cue help cmd greet
Usage:
  cue cmd greet [flags]

Flags:
  -h, --help   help for greet

Global Flags:
  -E, --all-errors   print all available errors
  -i, --ignore       proceed in the presence of errors
  -s, --simplify     simplify output
      --strict       report errors for lossy mappings
      --trace        trace computation
  -v, --verbose      print information about progress
$
```

**Comment by mpvl** [comment]
This seems to be a bug in Cobra. Cobra should have generated the documentation:

```
cue cmd [flags] greet
```

The flags need to be specified before the "subcommand" greet. This behavior is enabled by Cobra's `SetInterspersed(false)` feature to allow future compatibility in case we want to support using flags for commands.

**Comment by mpvl** [comment]
The solution would be for someone to file/track an issue in Cobra or submit a fix to Cobra. It could be that a later version of Cobra already fixes this.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/925.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
