### ISSUE TITLE
Doc/Ref: Invalid CUE expression in the Expressions section of doc/ref/spec.md

### ISSUE THREAD

**Issue by PierreR** [cuelang/cue#939]
In the "Primary expressions" of the  [spec ](https://github.com/cuelang/cue/blame/master/doc/ref/spec.md#L1904) the line `a: (1|2, 1)` does not seem to be a valid CUE expression:

### What version of CUE ?
https://tip.cuelang.org/play/?id=IfXze6I0s0D#cue@export@cue

**Comment by mpvl** [comment]
Wow. nice catch. You found a very old piece of spec that has relevance to the current CUE whatsoever. :)

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/939.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
