### ISSUE TITLE
Incorrect deprecation message

### ISSUE THREAD

**Issue by niemeyer** [cuelang/cue#945]
Just a simple one I stumbled upon while experimenting:

Having line 3 with `one=1` yields the following error message:
```
old-style alias; use "let X = expr" deprecated as of v0.1.4: try running `cue fix` using CUE v0.2.2 on the file or module to upgrade:
    ./test.cue:10:2
```
This probably intends to say that one _should_ use `let`, but it reads as if it is `let` that was deprecated.

The line number is also incorrect. The expression is on line 3, but it points instead to the next non-empty line at 10.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/945.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
