### ISSUE TITLE
documentation: Modify the confusing tour/references/aliases page

### ISSUE THREAD

**Issue by PierreR** [cuelang/cue#948]
**Documentation of aliases & let**

The following page of the doc refering to `aliases` is using the `let` construct:
https://cuelang.org/docs/tutorials/tour/references/aliases/

But to be honest I am not sure if the page is meant to introduce the concept of `aliases` or the `let` construct. These two are treated in the spec.md as two different concepts (with different use cases).

**Describe the solution you'd like**

I suggest to align the page with the spec.md to avoid confusion.

To the best of my knowledge a more idiomatic way to write the code snippet of the aliases page would be:
```
A=a: {
    d: 3
}
b: {
    a: {
        // A provides access to the outer "a" which would
        // otherwise be hidden by the inner one.
        c: A.d
    }
}
```

**Comment by mpvl** [comment]
This is an artifact of the time when there was no `let` and the same syntax/terminology was used to describe both. 

This is indeed very misleading and should be fixed.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/948.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
