### ISSUE TITLE
Too early evaluation?

### ISSUE THREAD

**Issue by kumorid** [cuelang/cue#955]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

I am trying to circumvent the problem reported in issue 951 by avoiding dijunctions of structs, opting for optional fields, but requiring exactly one of them to be provided.

The code I come up with is shown in file `test.cue` below.

However, when executing `cue export test.cue` I get the error reported below. 

<pre>
-- test.cue --
#T: {
  a?: int
  b?: int

  _A: a != _|_ 
  _B: b != _|_ 

  _valid: ((!_A && _B) || (_A && !_B)) & true
}

d: #T & {a: 56}

</pre>

### What did you expect to see?
<pre>
{
  "d": {
     "a": 56
  }
}
</pre>

### What did you see instead?

<pre>
#T._valid: conflicting values true and false:
    ./test.cue:8:12
    ./test.cue:8:42
</pre>

It looks like field `_valid` is evaluated very early, resulting in bottom, provoking the error message.

However, if instead of the above code I use the following (removed unification with `true` in `_valid`):

<pre>
-- test.cue --
#T: {
  a?: int
  b?: int

  _A: a != _|_ 
  _B: b != _|_ 

  _valid: ((!_A && _B) || (_A && !_B))

}

d: #T & {a: 56, _valid: _, _valid2: _valid & true}
</pre>

Then I get the expected result above. I.e, `_valid` is not computed early...

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/955.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
