### ISSUE TITLE
Field not allowed error may be confusing

### ISSUE THREAD

**Issue by niemeyer** [cuelang/cue#956]
Another trivial:
```
foo.bar: field type not allowed:
(...)
```
The message is confusing because "type" is the field name. It needs be quoted so it's not embedded in the message.

**Comment by mpvl** [comment]
We went back and forth on this.

**Comment by mpvl** [comment]
@niemeyer   It may get ugly when a field itself is already quoted. Could you imagine an alternative wording so that it is clearer that `type` and is a name?

**Comment by niemeyer** [comment]
The usual trick we do in those cases is to move the variable to the end of the line. Something like:
```
foo.bar: field not allowed: type
```
Alternatively, it might be inlined back into the prefix:
```
foo.bar.type: field not allowed
```

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/956.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
