### ISSUE TITLE
Inline struct is broken when cue fmt'ed

### ISSUE THREAD

**Issue by niemeyer** [cuelang/cue#958]
When `cue fmt` runs on this:
```
test: {...{[string]: int}}
```
It becomes this:
```
test: {..., {[string]: int}}
```

**Comment by mpvl** [comment]
This is because specifying types for additional field has not yet been implemented yet. Of course the parser should complain here about this. 

This is just a shorthand for `[string]: int`, though, to be consistent with the list notation. So for now you can use that.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/958.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
