### ISSUE TITLE
`cue cmd` reports "cycle error" instead of "undefined field"

### ISSUE THREAD

**Issue by niemeyer** [cuelang/cue#962]
This example:
```
foo: bar: "something"

command: test: {
    task: print: cli.Print & {
        _what: string @tag(what)
        _obj:  foo[_what]
        text:  yaml.Marshal(_obj)
    }
}
```
Will generate this error when `what` either isn't injected or is injected with a value that doesn't match an existing key in `foo`:
```
command.test.task.print.text: invalid string argument: cycle error:
    ./test_tool.cue:11:8
    ./test_tool.cue:14:3
    tool/cli:4:3
```

---

But it works as expected (that is, it errors correctly) if we remove the `_obj` indirection:
```
command: test: {
    task: print: cli.Print & {
        _what: string @tag(what)
        text:  yaml.Marshal(foo[_what])
    }
}
```
```
$ cue cmd test            
command.test.task.print.text: invalid string argument: invalid non-ground value string (must be concrete string):
    ./test_tool.cue:11:8
    ./test_tool.cue:13:3
    tool/cli:4:3

$ cue cmd -t what=baz test
command.test.task.print.text: invalid string argument: undefined field baz:
    ./test_tool.cue:11:8
    ./test_tool.cue:13:3
    ./test_tool.cue:13:27
    tool/cli:4:3
```

**Comment by mpvl** [comment]
FTR, this is a smaller reproducer:

```
import "encoding/yaml"

foo: bar: "something"

text:  yaml.Marshal(_obj)

_what: string
_obj:  foo[_what]
```

Note that the order matters here. The "cycle error" is used as a sentinel to detect cycles. As the first argument is a scalar, it only does a partial evaluation, which means the cycle error sentinel may not be eliminated yet for certain orders of evaluation.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/962.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
