### ISSUE TITLE
Field name gets embedded into "undefined field" error message

### ISSUE THREAD

**Issue by niemeyer** [cuelang/cue#963]
Another trivial which is a follow up of #956 (fixed with 3fdad16):

In this error message, the field name is embedded in the message: 
```
foo: undefined field type:
(...)
```
The `type` here is actually the field name, so this or other words that get embedded into the meaning (type, name, length, path, etc) make the error a bit confusing.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/963.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
