### ISSUE TITLE
Optional field syntax listed in spec produces error `d: { [string]?: string }` 

### ISSUE THREAD

**Issue by rudolph9** [cuelang/cue#97]
`d: { [string]?: string }`  produces an error.  It was taken strait from the spec doc on structs https://github.com/cuelang/cue/blob/master/doc/ref/spec.md#structs

Error:
```
cue eval filename.cue 
missing ',' in file:
    ./filename.cue:1:14
terminating because of errors
```

where the contents of `filename.cue` is:
```
d: { [string]?: string }
```

**Comment by mpvl** [comment]
Ah, this part of the spec was (temporarily) removed in the review process. But this example slipped through the cracks. It should be removed for now.

**Comment by xinau** [comment]
I've created the followin CL for removal. https://cue-review.googlesource.com/c/cue/+/3104

**Comment by mpvl** [comment]
It was removed

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/97.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
